osism/ansible-collection-services

- .github/workflows/test-sysdig.yml
- README.md
- molecule/sysdig/ansible.cfg
- molecule/sysdig/converge.yml
- molecule/sysdig/create.yml
- molecule/sysdig/destroy.yml
- molecule/sysdig/group_vars/all.yml
- molecule/sysdig/molecule.yml
- molecule/sysdig/prepare.yml
- molecule/sysdig/tests/test_default.py
- roles/sysdig/.information.yml
- roles/sysdig/README.md
- roles/sysdig/defaults/main.yml
- roles/sysdig/gilt.yml
- roles/sysdig/meta/main.yml
- roles/sysdig/tasks/install-Debian.yml
- roles/sysdig/tasks/main.yml
Imported from https://github.com/osism/ansible-sysdig
> Add osism.sysdig ansible role

- roles/falco/tasks/install-Debian.yml
> falco: load + persist kernel module

- .github/workflows/test-rsyslog.yml
- README.md
- molecule/rsyslog/ansible.cfg
- molecule/rsyslog/converge.yml
- molecule/rsyslog/create.yml
- molecule/rsyslog/destroy.yml
- molecule/rsyslog/group_vars/all.yml
- molecule/rsyslog/molecule.yml
- molecule/rsyslog/prepare.yml
- molecule/rsyslog/tests/test_default.py
- roles/rsyslog/.information.yml
- roles/rsyslog/README.md
- roles/rsyslog/defaults/main.yml
- roles/rsyslog/gilt.yml
- roles/rsyslog/handlers/main.yml
- roles/rsyslog/meta/main.yml
- roles/rsyslog/tasks/fluentd.yml
- roles/rsyslog/tasks/main.yml
- roles/rsyslog/templates/70-fluentd.conf.j2
- roles/rsyslog/templates/rsyslog.conf.j2
Imported from https://github.com/osism/ansible-rsyslog
> Add osism.rsyslog ansible role

- .github/workflows/test-cockpit.yml
- README.md
- molecule/cockpit/ansible.cfg
- molecule/cockpit/converge.yml
- molecule/cockpit/create.yml
- molecule/cockpit/destroy.yml
- molecule/cockpit/group_vars/all.yml
- molecule/cockpit/molecule.yml
- molecule/cockpit/prepare.yml
- molecule/cockpit/requirements.yml
- molecule/cockpit/tests/test_default.py
- roles/cockpit/.information.yml
- roles/cockpit/README.md
- roles/cockpit/defaults/main.yml
- roles/cockpit/files/cockpit.conf
- roles/cockpit/gilt.yml
- roles/cockpit/handlers/main.yml
- roles/cockpit/meta/main.yml
- roles/cockpit/tasks/main.yml
- roles/cockpit/tasks/server.yml
- roles/cockpit/templates/listen.conf.j2
- roles/cockpit/templates/machine.json.j2
- roles/cockpit/vars/ubuntu-18.04.yml
- roles/cockpit/vars/ubuntu-20.04.yml
> Add cockpit role

- .github/workflows/test-phpmyadmin.yml
- README.md
- molecule/phpmyadmin/ansible.cfg
- molecule/phpmyadmin/converge.yml
- molecule/phpmyadmin/create.yml
- molecule/phpmyadmin/destroy.yml
- molecule/phpmyadmin/group_vars/all.yml
- molecule/phpmyadmin/molecule.yml
- molecule/phpmyadmin/prepare.yml
- molecule/phpmyadmin/requirements.yml
- roles/phpmyadmin/defaults/main.yml
- roles/phpmyadmin/tasks/main.yml
- roles/phpmyadmin/templates/docker-compose.yml.j2
> Add phpmyadmin role

- molecule/auditd/create.yml
- molecule/auditd/destroy.yml
- molecule/cockpit/create.yml
- molecule/cockpit/destroy.yml
- molecule/falco/create.yml
- molecule/falco/destroy.yml
- molecule/osquery/create.yml
- molecule/osquery/destroy.yml
- molecule/phpmyadmin/create.yml
- molecule/phpmyadmin/destroy.yml
- molecule/rsyslog/create.yml
- molecule/rsyslog/destroy.yml
- roles/auditd/tasks/main.yml
> ansible-lint: fix E208

- gilt.yml
> Add gilt.yml file

- roles/auditd/handlers/main.yml
- roles/auditd/tasks/main.yml
- roles/cockpit/handlers/main.yml
- roles/cockpit/tasks/main.yml
- roles/cockpit/tasks/server.yml
- roles/falco/tasks/install-Debian.yml
- roles/osquery/handlers/main.yml
- roles/osquery/tasks/install-Debian.yml
- roles/osquery/tasks/main.yml
- roles/phpmyadmin/tasks/main.yml
- roles/rsyslog/handlers/main.yml
- roles/rsyslog/tasks/fluentd.yml
- roles/rsyslog/tasks/main.yml
> Move "become" to the top of the tasks

- roles/patchman/.information.yml
- roles/patchman/README.md
- roles/patchman/defaults/main.yml
- roles/patchman/gilt.yml
- roles/patchman/meta/main.yml
- roles/patchman/tasks/main.yml
- roles/patchman/tasks/update.yml
- roles/patchman/templates/docker-compose.yml.j2
- roles/patchman/templates/env/patchman.env.j2
- roles/patchman/templates/env/postgres.env.j2
- roles/patchman/templates/local_settings.py.j2
- roles/patchman/templates/patchman-update.j2
- roles/patchman_client/.information.yml
- roles/patchman_client/README.md
- roles/patchman_client/defaults/main.yml
- roles/patchman_client/files/patchman-client
- roles/patchman_client/gilt.yml
- roles/patchman_client/meta/main.yml
- roles/patchman_client/tasks/main.yml
- roles/patchman_client/tasks/update.yml
- roles/patchman_client/templates/patchman-client.conf.j2
Molecule & workflows will be added later.
> Add patchman roles (#19)

- roles/adminer/.information.yml
- roles/adminer/README.md
- roles/adminer/defaults/main.yml
- roles/adminer/gilt.yml
- roles/adminer/meta/main.yml
- roles/adminer/tasks/main.yml
- roles/adminer/templates/docker-compose.yml.j2
Molecule & workflows will be added later.
> Add adminer role

- roles/pulp/.information.yml
- roles/pulp/README.md
- roles/pulp/defaults/main.yml
- roles/pulp/gilt.yml
- roles/pulp/meta/main.yml
- roles/pulp/tasks/main.yml
- roles/pulp/templates/docker-compose.yml.j2
- roles/pulp/templates/settings.py.j2
Molecule & workflows will be added later.
> Add pulp role

- roles/ucs/.information.yml
- roles/ucs/README.md
- roles/ucs/defaults/main.yml
- roles/ucs/gilt.yml
- roles/ucs/meta/main.yml
- roles/ucs/tasks/main.yml
- roles/ucs/templates/docker-compose.yml.j2
- roles/ucs/templates/env/ucs.env.j2
Molecule & workflows will be added later.
> Add ucs role

- molecule/requirements.txt
Test was moved to Github workflows.
> molecule: remove ansible-lint requirement

- roles/hddtemp/.information.yml
- roles/hddtemp/README.md
- roles/hddtemp/defaults/main.yml
- roles/hddtemp/files/hddtemp
- roles/hddtemp/gilt.yml
- roles/hddtemp/handlers/main.yml
- roles/hddtemp/meta/main.yml
- roles/hddtemp/tasks/main.yml
- roles/rng/.information.yml
- roles/rng/README.md
- roles/rng/defaults/main.yml
- roles/rng/gilt.yml
- roles/rng/meta/main.yml
- roles/rng/tasks/main.yml
- roles/smartd/.information.yml
- roles/smartd/README.md
- roles/smartd/defaults/main.yml
- roles/smartd/files/smartmontools
- roles/smartd/gilt.yml
- roles/smartd/handlers/main.yml
- roles/smartd/meta/main.yml
- roles/smartd/tasks/main.yml
> Add services from osism.commons

- roles/keycloak/.information.yml
- roles/keycloak/README.md
- roles/keycloak/defaults/main.yml
- roles/keycloak/gilt.yml
- roles/keycloak/meta/main.yml
- roles/keycloak/tasks/main.yml
- roles/keycloak/templates/docker-compose.yml.j2
- roles/keycloak/templates/env/keycloak.env.j2
- roles/keycloak/templates/env/postgres.env.j2
> Add keycloak role

- README.md
> README: add missing roles

- README.md
> README: cleanup & add missing roles

- roles/manager/defaults/main.yml
> manager: updates versions & use quay.io for ansible images

- README.md
- roles/openstack_health_monitor/README.md
- roles/openstack_health_monitor/defaults/main.yml
- roles/openstack_health_monitor/meta/main.yml
- roles/openstack_health_monitor/tasks/container-Debian.yml
- roles/openstack_health_monitor/tasks/main.yml
- roles/openstack_health_monitor/templates/docker-compose.yml.j2
- roles/openstack_health_monitor/templates/env/openstack_health_monitor.env.j2
> Add openstack_health_monitor role

- roles/openstack_health_monitor/defaults/main.yml
- roles/openstack_health_monitor/tasks/container-Debian.yml
- roles/openstack_health_monitor/templates/env/openstack_health_monitor.env.j2
> Improve openstack_health_monitor role

- roles/openstack_health_monitor/defaults/main.yml
- roles/openstack_health_monitor/tasks/container-Debian.yml
- roles/openstack_health_monitor/templates/docker-compose.yml.j2
- roles/openstack_health_monitor/templates/env/openstack_health_monitor.env.j2
> Fix openstack_health_monitor role

- roles/openstack_health_monitor/defaults/main.yml
- roles/openstack_health_monitor/templates/docker-compose.yml.j2
> openstack_health_monitor: logs -> data

- roles/cephclient/defaults/main.yml
- roles/manager/defaults/main.yml
- roles/openstackclient/defaults/main.yml
> Use quay registry

- .github/playbook-publish-collection.yml
- .github/templates/galaxy.yml.j2
- .github/workflows/publish-collection.yml
- .gitignore
> github: enable 'Publish collection' workflow

- roles/adminer/defaults/main.yml
- roles/cephclient/defaults/main.yml
- roles/openstack_health_monitor/defaults/main.yml
- roles/openstackclient/defaults/main.yml
- roles/patchman/defaults/main.yml
- roles/phpmyadmin/defaults/main.yml
- roles/pulp/defaults/main.yml
- roles/ucs/defaults/main.yml
- roles/zabbix/defaults/main.yml
> Add more docker_registry variables

- .information.yml
- gilt.yml
> Remove gilt configuration

- .github/workflows/check-yaml-syntax.yml
- .yamllint.yml
- molecule/default/prepare/chrony.yml
- molecule/default/prepare/rng.yml
- roles/auditd/tasks/main.yml
- roles/cephclient/defaults/main.yml
- roles/cephclient/tasks/package-Debian.yml
- roles/chrony/defaults/main.yml
- roles/chrony/tasks/main.yml
- roles/hddtemp/tasks/main.yml
- roles/openstackclient/defaults/main.yml
- roles/openstackclient/tasks/package-Debian.yml
- roles/osquery/defaults/main.yml
- roles/osquery/tasks/install-Debian.yml
- roles/patchman/defaults/main.yml
- roles/patchman_client/defaults/main.yml
- roles/rng/tasks/main.yml
- roles/smartd/tasks/main.yml
- roles/zabbix_agent/defaults/main.yml
- roles/zabbix_agent/tasks/config.yml
- roles/zabbix_agent/tasks/install-Debian.yml
> Fix yamllint issues

- roles/manager/defaults/main.yml
> manager: add more registry variables

- roles/manager/templates/env/awx.env.j2
> manager: add CEPH to awx env file

- roles/cephclient/defaults/main.yml
- roles/openstackclient/defaults/main.yml
> Enforce quay registry for openstack/cephclient images

- roles/openstackclient/templates/docker-compose.yml.j2
> openstackclient: use sleep infinity

- roles/manager/templates/docker-compose.yml.j2
> manager: add awx inventory volume

- roles/manager/defaults/main.yml
- roles/manager/tasks/config-awx.yml
- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/env/awxclient.env.j2
> manager: add awxclient

- roles/manager/defaults/main.yml
> manager: fix awxclient tag

- roles/manager/templates/docker-compose.yml.j2
> manager: add missing awxxclient.env file

- roles/manager/templates/awx/settings.py.j2
> manager: set AWX_REBUILD_SMART_MEMBERSHIP

- roles/manager/templates/awx/nginx.conf.j2
> manager: remove Content-Security-Policy from awx nginx configuration

- roles/patchman/defaults/main.yml
> patchman: use quay registry

- roles/manager/defaults/main.yml
- roles/manager/templates/awx/settings.py.j2
> manager: improve awx configuration

- roles/manager/templates/awx/settings.py.j2
> manager: remove , from awx settings

- roles/manager/defaults/main.yml
> manager: use ara 1.5.4

- roles/manager/defaults/main.yml
> manager: add deploy_private_key

- roles/auditd/tasks/main.yml
- roles/cephclient/tasks/package-Debian.yml
- roles/chrony/tasks/main.yml
- roles/cockpit/tasks/main.yml
- roles/cockpit/tasks/server.yml
- roles/docker/tasks/install-docker-Debian.yml
- roles/docker/tasks/install-kata-Debian.yml
- roles/falco/tasks/install-Debian.yml
- roles/hddtemp/tasks/main.yml
- roles/manager/tasks/install-Debian.yml
- roles/netdata/tasks/install-Debian.yml
- roles/openstackclient/tasks/package-Debian.yml
- roles/osquery/tasks/install-Debian.yml
- roles/patchman_client/tasks/main.yml
- roles/rng/tasks/main.yml
- roles/rsyslog/tasks/main.yml
- roles/smartd/tasks/main.yml
- roles/zabbix_agent/tasks/install-Debian.yml
> Wait for /var/lib/dpkg/lock

- roles/auditd/tasks/main.yml
- roles/cephclient/tasks/package-Debian.yml
- roles/chrony/tasks/main.yml
- roles/cockpit/tasks/server.yml
- roles/docker/tasks/install-docker-Debian.yml
- roles/docker/tasks/install-kata-Debian.yml
- roles/falco/tasks/install-Debian.yml
- roles/hddtemp/tasks/main.yml
- roles/manager/tasks/install-Debian.yml
- roles/netdata/tasks/install-Debian.yml
- roles/openstackclient/tasks/package-Debian.yml
- roles/osquery/tasks/install-Debian.yml
- roles/patchman_client/tasks/main.yml
- roles/rng/tasks/main.yml
- roles/rsyslog/tasks/main.yml
- roles/zabbix_agent/tasks/install-Debian.yml
> Improve "Wait for /var/lib/dpkg/lock"

- roles/auditd/tasks/install-Debian.yml
- roles/auditd/tasks/main.yml
- roles/chrony/tasks/install-Debian.yml
- roles/chrony/tasks/main.yml
- roles/cockpit/tasks/install-Debian.yml
- roles/cockpit/tasks/install-server-Debian.yml
- roles/cockpit/tasks/main.yml
- roles/cockpit/tasks/server.yml
- roles/hddtemp/tasks/install-Debian.yml
- roles/hddtemp/tasks/main.yml
- roles/patchman_client/tasks/install-Debian.yml
- roles/patchman_client/tasks/main.yml
- roles/rng/tasks/install-Debian.yml
- roles/rng/tasks/main.yml
- roles/rsyslog/tasks/install-Debian.yml
- roles/rsyslog/tasks/main.yml
- roles/smartd/tasks/install-Debian.yml
- roles/smartd/tasks/main.yml
> Add install-Debian.yml files

- galaxy.yml
> galaxy: v0.2.0

- roles/auditd/templates/rules/20-neo23x0.rules.j2
> auditd: update neo23x0.rules

- roles/auditd/templates/rules/20-neo23x0.rules.j2
> auditd: ignore /usr/bin/dockerd

- roles/auditd/templates/rules/20-neo23x0.rules.j2
> auditd: ignore /var/lib/docker

- roles/rsyslog/defaults/main.yml
- roles/rsyslog/tasks/main.yml
- roles/rsyslog/templates/70-fluentd.conf.j2
> Improve fluentd parameters

- roles/manager/defaults/main.yml
- roles/manager/templates/env/ara-server.env.j2
> manager: make number of ara workers configurable

- README.md
- roles/fail2ban/defaults/main.yml
- roles/fail2ban/meta/main.yml
- roles/fail2ban/tasks/install-Debian.yml
- roles/fail2ban/tasks/main.yml
> Add fail2ban role

- roles/netdata/defaults/main.yml
- roles/netdata/tasks/deploy.yml
- roles/netdata/tasks/main.yml
> netdata: overall improvements

- roles/netdata/tasks/config.yml
> netdata: create /var/lib/netdata/cloud.d directory

- roles/netdata/defaults/main.yml
- roles/netdata/templates/netdata.conf.j2
> netdata: add netdata_memory_mode

- roles/netdata/defaults/main.yml
- roles/netdata/templates/netdata.conf.j2
> netdata: add netdata_update_every

- roles/netdata/templates/netdata.conf.j2
> netdata: disable access logs on the server

- roles/netdata/defaults/main.yml
- roles/netdata/templates/stream.conf.j2
> netdata: add netdata_default_history

- README.md
- roles/bird/defaults/main.yml
- roles/bird/handlers/main.yml
- roles/bird/meta/main.yml
- roles/bird/tasks/install-Debian.yml
- roles/bird/tasks/main.yml
- roles/bird/templates/bird.conf.j2
> Add bird role

- roles/bird/defaults/main.yml
- roles/bird/templates/bird.conf.j2
> bird: add more parameters

- roles/zabbix/defaults/main.yml
- roles/zabbix/templates/env/zabbix-web.env.j2
> zabbix: overall improvements

- roles/zabbix_agent/tasks/cleanup-Debian.yml
- roles/zabbix_agent/tasks/config.yml
- roles/zabbix_agent/tasks/install-Debian.yml
- roles/zabbix_agent/tasks/main.yml
> zabbix_agent: remove old zabbix-agent package

- roles/zabbix_agent/tasks/main.yml
> zabbix_agent: cleanup first

- roles/zabbix_agent/tasks/cleanup-Debian.yml
> zabbix_agent: check if old service is available

- plugins/modules/scan_services.py
> Add scan_services module

- roles/manager/defaults/main.yml
- roles/manager/tasks/config-ara.yml
- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/env/ara-server.env.j2
> manager: make ara database backend configurable

- roles/zabbix_agent/defaults/main.yml
> zabbix_agent: use version 5.2

- roles/zabbix_agent/tasks/install-Debian.yml
> zabbix_agent: use copy to manage the repository

- roles/zabbix_agent/tasks/install-Debian.yml
> zabbix_agent: install latest package

- roles/netdata/tasks/install-Debian.yml
> netdata: install latest package

- roles/netdata/handlers/main.yml
- roles/netdata/tasks/config.yml
- roles/netdata/tasks/install-Debian.yml
> netdata: restart service after package upgrade

- roles/zabbix_agent/handlers/main.yml
- roles/zabbix_agent/tasks/agent-extension.yml
- roles/zabbix_agent/tasks/config.yml
- roles/zabbix_agent/tasks/install-Debian.yml
- roles/zabbix_agent/tasks/main.yml
> zabbix_agent: restart service after package upgrade

- roles/falco/handlers/main.yml
- roles/falco/tasks/install-Debian.yml
> falco: install latest package & restart falco service after an upgrade

- roles/osquery/handlers/main.yml
- roles/osquery/tasks/install-Debian.yml
> osquery: install latest package & restart service after an upgrade

- roles/adminer/defaults/main.yml
- roles/adminer/tasks/main.yml
- roles/cephclient/defaults/main.yml
- roles/cephclient/tasks/container-Debian.yml
- roles/openstackclient/defaults/main.yml
- roles/openstackclient/tasks/container-Debian.yml
- roles/phpmyadmin/defaults/main.yml
- roles/phpmyadmin/tasks/main.yml
> Use docker-compose service (pt. 1)

- roles/zabbix/defaults/main.yml
- roles/zabbix/tasks/main.yml
> zabbix: use docker-compose service

- roles/patchman/defaults/main.yml
- roles/patchman/tasks/main.yml
> patchman: use docker-compose service

- roles/manager/defaults/main.yml
- roles/manager/tasks/service.yml
> manager: use docker-compose service

- roles/manager/defaults/main.yml
- roles/patchman/defaults/main.yml
> Fix wrong docker-compose service names

- galaxy.yml
> galaxy: v0.3.0

- roles/docker/defaults/main.yml
> docker: use version 20.10.5

- roles/netbox/defaults/main.yml
- roles/netbox/tasks/config-netbox.yml
- roles/netbox/tasks/config-postgres.yml
- roles/netbox/templates/docker-compose.yml.j2
> netbox: minor fixes

- roles/netbox/defaults/main.yml
- roles/netbox/templates/docker-compose.yml.j2
> netbox: minor fixes (pt. 2)

- galaxy.yml
> galaxy: 0.4.0

- roles/manager/defaults/main.yml
> manager: use awxclient 19.0.0

- README.md
- roles/minikube/defaults/main.yml
- roles/minikube/meta/main.yml
- roles/minikube/tasks/main.yml
> Add minimal minikube role

- roles/minikube/defaults/main.yml
- roles/minikube/tasks/main.yml
- roles/minikube/templates/minikube.service.j2
> minikube: add service

- roles/minikube/defaults/main.yml
- roles/minikube/tasks/main.yml
- roles/minikube/templates/minikube.service.j2
> minikube: fix some smaller issues

- roles/netbox/defaults/main.yml
> netbox: fix service name

- roles/manager/tasks/config-awx.yml
- roles/manager/templates/awx/nginx.conf.j2
- roles/manager/templates/docker-compose.yml.j2
> manager: restart nginx configuration of awx

- roles/manager/defaults/main.yml
- roles/manager/templates/env/awx.env.j2
> manager: add awx_group_queues parameter

- roles/manager/defaults/main.yml
> manager: do not use 00000000-0000-0000-0000-000000000000 for awx

- roles/manager/templates/docker-compose.yml.j2
> manager: remove awx-web container

- roles/manager/templates/docker-compose.yml.j2
> manager: fix broken dependency

- .github/workflows/test-role-chrony.yml
- .github/workflows/test-role-rng.yml
> Add missing quotes

- roles/manager/handlers/main.yml
- roles/manager/tasks/service.yml
> manager: restart service after a change in docker-compose.yml

- roles/rundeck/defaults/main.yml
- roles/rundeck/templates/env/rundeck.env.j2
> Fix rundeck configuration

- roles/rundeck/templates/env/postgres.env.j2
> Fix rundeck configuration (pt. 2)

- roles/rundeck/templates/docker-compose.yml.j2
> rundeck: add keystore volume

- roles/manager/defaults/main.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: add inventory-reconciler service

- roles/manager/templates/docker-compose.yml.j2
> manager: use inventory-reconciler for awx

- roles/docker/tasks/bootstrap.yml
- roles/docker/tasks/install-docker-Debian.yml
> docker: ensure that docker_registry_username is a string

- roles/docker/defaults/main.yml
- roles/docker/handlers/main.yml
> docker: add docker_allow_restart parameter

- roles/manager/defaults/main.yml
- roles/manager/templates/env/ara-server.env.j2
> manager: add ara_worker_class parameter

- roles/manager/defaults/main.yml
> manager: restore defaults

- roles/manager/templates/docker-compose.yml.j2
> manager: add netbox details to the inventory_reconciler container

- roles/manager/templates/wrapper/osism-update-manager.j2
> manager: add missing secrets.yml to osism-update-manager script

- roles/patchman/defaults/main.yml
- roles/patchman/templates/docker-compose.yml.j2
> patchman: fix memcached image

- README.md
- roles/heimdall/defaults/main.yml
- roles/heimdall/meta/main.yml
- roles/heimdall/tasks/main.yml
- roles/heimdall/templates/docker-compose.yml.j2
> Add heimdall role

- roles/heimdall/defaults/main.yml
- roles/heimdall/tasks/main.yml
- roles/heimdall/templates/docker-compose.yml.j2
> heimdall: fix some nits

- roles/heimdall/defaults/main.yml
> heimdall: use image from osism

- roles/heimdall/defaults/main.yml
- roles/heimdall/templates/docker-compose.yml.j2
> heimdall: add parameters

- roles/netbox/templates/docker-compose.yml.j2
> netbox: add healthcheck

- README.md
- roles/jenkins/defaults/main.yml
- roles/jenkins/meta/main.yml
- roles/jenkins/tasks/main.yml
- roles/jenkins/templates/docker-compose.yml.j2
> Add jenkins role

- roles/jenkins/defaults/main.yml
- roles/jenkins/tasks/main.yml
> jenkins: add missing parameter

- roles/jenkins/defaults/main.yml
> jenkins: use custom image

- roles/manager/templates/docker-compose.yml.j2
> manager: add interface volume

- roles/manager/templates/docker-compose.yml.j2
> manager: add configuration volume

- roles/manager/defaults/main.yml
- roles/manager/templates/awx/credentials.py.j2
- roles/manager/templates/awx/settings.py.j2
- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/env/awx.env.j2
> manager: minor improvements

- roles/cockpit/tasks/install-Debian.yml
- roles/cockpit/tasks/install-server-Debian.yml
- roles/docker/tasks/install-docker-Debian.yml
- roles/manager/tasks/install-Debian.yml
> Do not use loops with the apt task

- meta/runtime.yml
> meta: fix required ansible version

- roles/patchman/defaults/main.yml
> patchman: use postgres 13

- roles/rng/meta/main.yml
- roles/rng/tasks/install-RedHat.yml
> feature redhat for role rng

- roles/docker/tasks/main.yml
> feature redhat for role docker, fail if not Debian

- roles/adminer/meta/main.yml
- roles/auditd/meta/main.yml
- roles/cephclient/meta/main.yml
- roles/chrony/meta/main.yml
- roles/cockpit/meta/main.yml
- roles/docker/meta/main.yml
- roles/fail2ban/meta/main.yml
- roles/falco/meta/main.yml
- roles/hddtemp/meta/main.yml
- roles/heimdall/meta/main.yml
- roles/jenkins/meta/main.yml
- roles/keycloak/meta/main.yml
- roles/manager/meta/main.yml
- roles/minikube/meta/main.yml
- roles/netbox/meta/main.yml
- roles/netdata/meta/main.yml
- roles/openldap/meta/main.yml
- roles/openstack_health_monitor/meta/main.yml
- roles/openstackclient/meta/main.yml
- roles/patchman/meta/main.yml
- roles/patchman_client/meta/main.yml
- roles/phpmyadmin/meta/main.yml
- roles/rng/meta/main.yml
- roles/rsyslog/meta/main.yml
- roles/rundeck/meta/main.yml
- roles/smartd/meta/main.yml
- roles/ucs/meta/main.yml
- roles/zabbix/meta/main.yml
- roles/zabbix_agent/meta/main.yml
Signed-off-by: Tim Beermann <beermann@osism.tech>
> Company name changed

- roles/zabbix/tasks/main.yml
- roles/zabbix_agent/tasks/main.yml
> Deprecate zabbix support

- .github/scripts/generate-role-workflows.sh
- .github/templates/test-role.yml.j2
- .github/workflows/test-role-chrony.yml
- molecule/default/collections.yml
- molecule/default/molecule.yml
> github: fix molecule jobs

- .github/scripts/generate-role-workflows.sh
- .github/templates/test-role.yml.j2
- .github/workflows/test-role-chrony.yml
- .github/workflows/test-role-rng.yml
> github: add molecule_scenario

- galaxy.yml
> galaxy: 0.5.0

- roles/manager/templates/docker-compose.yml.j2
> manager: allow Netbox integration without AWX integration

- roles/openldap/defaults/main.yml
- roles/openldap/tasks/main.yml
- roles/openldap/templates/docker-compose.yml.j2
- roles/openldap/templates/env/udm-rest.env.j2
> Add UDM-REST service to OpenLDAP

- roles/adminer/handlers/main.yml
- roles/adminer/tasks/main.yml
- roles/netbox/handlers/main.yml
- roles/netbox/tasks/service.yml
- roles/openstackclient/handlers/main.yml
- roles/openstackclient/tasks/container-Debian.yml
> Add missing notifications for changes to docker-compose files (pt. 1)

- roles/openldap/defaults/main.yml
- roles/openldap/tasks/main.yml
- roles/openldap/templates/docker-compose.yml.j2
- roles/openldap/templates/env/umc-gateway.env.j2
- roles/openldap/templates/env/umc-server.env.j2
- roles/openldap/templates/env/umc-web.env.j2
- roles/openldap/templates/umc/gateway/ucr.j2
- roles/openldap/templates/umc/server/ucr.j2
- roles/openldap/templates/umc/web/ucr.j2
> Add UMC service to OpenLDAP

- roles/openldap/templates/docker-compose.yml.j2
> Add some missing "restart: unless-stopped" settings

- galaxy.yml
> galaxy: fix "authors list must not be greater than 64 characters"

- galaxy.yml
> galaxy: 0.6.0

- roles/keycloak/defaults/main.yml
> keycloak: use postgres 13

- roles/netbox/defaults/main.yml
- roles/netbox/templates/docker-compose.yml.j2
> netbox: use default postgres image

- roles/openldap/defaults/main.yml
- roles/openldap/templates/docker-compose.yml.j2
> openldap: add more port + host arguments

- roles/openldap/defaults/main.yml
> openldap: use correct fixed tags (#271)

- roles/openldap/templates/env/udm-rest.env.j2
- roles/openldap/templates/umc/gateway/ucr.j2
- roles/openldap/templates/umc/server/ucr.j2
- roles/openldap/templates/umc/web/ucr.j2
> openldap: removed unused ip variables (#273)

- README.md
> README: remove ucs role

- README.md
- roles/virtualbmc/defaults/main.yml
- roles/virtualbmc/handlers/main.yml
- roles/virtualbmc/meta/main.yml
- roles/virtualbmc/tasks/config.yml
- roles/virtualbmc/tasks/main.yml
- roles/virtualbmc/tasks/service.yml
- roles/virtualbmc/templates/docker-compose.yml.j2
> Add virtualbmc service

- roles/virtualbmc/defaults/main.yml
- roles/virtualbmc/tasks/config.yml
- roles/virtualbmc/templates/docker-compose.yml.j2
> virtualbmc: fix nits

- roles/virtualbmc/templates/docker-compose.yml.j2
> virtualbmc: remove healthcheck

- roles/virtualbmc/templates/docker-compose.yml.j2
> vbmcd open udp ports

- roles/openldap/defaults/main.yml
> openldap: update default image names and tags

- roles/netbox/defaults/main.yml
> netbox: use v3.0-ldap

- roles/netbox/templates/initializers/device_roles.yml.j2
- roles/netbox/templates/initializers/tags.yml.j2
> netbox: improve tags & device roles

- roles/netbox/templates/initializers/device_roles.yml.j2
> netbox: add switch device roles

- roles/netbox/templates/initializers/device_roles.yml.j2
> netbox: fix names of the switch device roles

- roles/docker/defaults/main.yml
- roles/docker/handlers/main.yml
> docker: do not restart the service on manager nodes by default

- galaxy.yml
> docs.osism.de -> docs.osism.tech

- roles/keycloak/defaults/main.yml
- roles/manager/defaults/main.yml
- roles/netbox/defaults/main.yml
> Use postgres 14

- roles/netbox/templates/initializers/device_roles.yml.j2
> netbox: add a generic-switch device role

- roles/netbox/templates/initializers/device_roles.yml.j2
> netbox: add a firewall-node device role

- roles/homer/templates/config.yml.j2
closes #353
Signed-off-by: Tim Beermann <beermann@osism.tech>
> homer: fixed light theme colour missmatch

- roles/keycloak/handlers/main.yml
- roles/keycloak/tasks/service.yml
> keycloak: do not restart the service if it was started before

- README.md
- roles/nexus/defaults/main.yml
- roles/nexus/meta/main.yml
- roles/nexus/tasks/main.yml
- roles/nexus/templates/docker-compose.yml.j2
> Add nexus role

- meta/runtime.yml
> meta: allow use of ansible 2.11

- roles/nexus/templates/docker-compose.yml.j2
> nexus: fix volume

- roles/nexus/handlers/main.yml
- roles/nexus/tasks/main.yml
- roles/nexus/templates/docker-compose.yml.j2
> nexus: add handler + backend ports

- roles/netbox/templates/initializers/tags.yml.j2
> netbox: add missing tags

- roles/netbox/templates/initializers/tags.yml.j2
> netbox: add ceph-resource tag

- roles/manager/defaults/main.yml
- roles/manager/files/awx/create-admin-user.sh
- roles/manager/files/awx/provision-instance.sh
- roles/manager/tasks/config-awx.yml
- roles/manager/tasks/initialize-awx.yml
- roles/manager/tasks/initialize.yml
- roles/manager/templates/awx/receptor.conf.j2
- roles/manager/templates/docker-compose.yml.j2
> manager: revision of the AWX service

- roles/manager/defaults/main.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: fix the receptor service

- roles/manager/tasks/config-awx.yml
- roles/manager/templates/awx/supervisord.conf.j2
- roles/manager/templates/docker-compose.yml.j2
> manager: add awx supervisord configuration

- roles/manager/templates/docker-compose.yml.j2
> manager: set interface volume to rw in awx service

- roles/netbox/defaults/main.yml
> netbox: user our own image

- roles/manager/defaults/main.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: run celery worker

- roles/manager/templates/docker-compose.yml.j2
> manager: fix wrong flower parameter names

- roles/manager/templates/docker-compose.yml.j2
> manager: add beat service

- roles/patchman_client/defaults/main.yml
- roles/patchman_client/tasks/update.yml
> patchman-client: add patchman_client_update_force

- roles/auditd/tasks/install-Debian.yml
- roles/cephclient/tasks/package-Debian.yml
- roles/chrony/tasks/install-Debian.yml
- roles/cockpit/tasks/install-Debian.yml
- roles/cockpit/tasks/install-server-Debian.yml
- roles/docker/tasks/install-docker-Debian.yml
- roles/docker/tasks/install-kata-Debian.yml
- roles/fail2ban/tasks/install-Debian.yml
- roles/falco/tasks/install-Debian.yml
- roles/hddtemp/tasks/install-Debian.yml
- roles/manager/tasks/install-Debian.yml
- roles/netdata/tasks/install-Debian.yml
- roles/openstackclient/tasks/package-Debian.yml
- roles/patchman_client/tasks/install-Debian.yml
- roles/rng/tasks/install-Debian.yml
- roles/rsyslog/tasks/install-Debian.yml
- roles/smartd/tasks/install-Debian.yml
- roles/tailscale/tasks/install-Debian.yml
partly: osism/issues#61
﻿Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
> changed wait for apt lock

- roles/manager/templates/docker-compose.yml.j2
> manager: add interface volume to the interface_reconciler service

- roles/manager/defaults/main.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: improve vault configuration

- roles/manager/templates/docker-compose.yml.j2
> manager: make vault usable without awx

- roles/manager/defaults/main.yml
- roles/manager/tasks/config-vault.yml
- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/vault.hcl.j2
> manager: use vault.hcl configuration file

- roles/manager/templates/env/vault.env.j2
> manager: remove VAULT_LOCAL_CONFIG from vault.env

- roles/manager/tasks/config-vault.yml
- roles/manager/templates/vault.hcl.j2
> manager: fix vault.hcl file permissions

- roles/docker/defaults/main.yml
- roles/docker/files/.gitattributes
- roles/docker/files/docker-compose-v2.0.1/.gitattributes
- roles/docker/files/docker-compose-v2.0.1/docker-compose-linux-x86_64.bin
- roles/docker/tasks/install-docker-compose.yml
- roles/docker/tasks/main.yml
> docker: install docker-compose cli plugin

- roles/docker/tasks/main.yml
> docker: fix wrong parameter name

- roles/homer/defaults/main.yml
> homer: fix internal flower url

- roles/nexus/defaults/main.yml
- roles/nexus/tasks/config.yml
- roles/nexus/tasks/main.yml
- roles/nexus/tasks/service.yml
- roles/nexus/templates/docker-compose.yml.j2
- roles/nexus/templates/nexus.properties.j2
> nexus: preparation for automation

- README.md
- roles/lldpd/defaults/main.yml
- roles/lldpd/handlers/main.yml
- roles/lldpd/meta/main.yml
- roles/lldpd/tasks/install-Debian.yml
- roles/lldpd/tasks/main.yml
- roles/lldpd/templates/auditd.conf.j2
- roles/lldpd/templates/rules/20-neo23x0.rules.j2
> Add lldpd role

- roles/nexus/tasks/config.yml
> nexus: fix copy & paste issue

- roles/nexus/defaults/main.yml
- roles/nexus/tasks/initialize.yml
- roles/nexus/tasks/main.yml
- roles/nexus/templates/docker-compose.yml.j2
> nexus: run scripts

- roles/nexus/tasks/initialize.yml
> nexus: add ubuntu-docker proxy

- roles/manager/templates/docker-compose.yml.j2
> manager: improve the celery support

- roles/manager/defaults/main.yml
- roles/manager/tasks/initialize-vault.yml
- roles/manager/tasks/initialize.yml
> manager: initialize vault

- roles/manager/defaults/main.yml
- roles/manager/tasks/initialize-vault.yml
> manager: output the generated key shares

- roles/manager/defaults/main.yml
- roles/manager/tasks/initialize-vault.yml
> manager: fix vault_key_shares_path

- roles/manager/templates/docker-compose.yml.j2
> manager: add two basic pgrep healthchecks

- roles/netbox/defaults/main.yml
- roles/netbox/templates/configuration.py.j2
> netbox: add plugins

- roles/netbox/defaults/main.yml
> netbox: add netbox_bgp plugin

- README.md
- roles/frr/defaults/main.yml
- roles/frr/handlers/main.yml
- roles/frr/meta/main.yml
- roles/frr/tasks/install-Debian.yml
- roles/frr/tasks/main.yml
> Add initial frr role

- roles/nexus/tasks/initialize.yml
> nexus: use ubuntu-archive script

- roles/nexus/defaults/main.yml
- roles/nexus/tasks/initialize.yml
> nexus: make provision scripts configurable

- roles/docker/defaults/main.yml
> docker: configure repository by default

- roles/manager/templates/wrapper/osism-update-manager.j2
> using node_id needs netaddr pip package installed

- roles/docker/defaults/main.yml
- roles/docker/tasks/config-zun.yml
- roles/docker/tasks/main.yml
- roles/docker/templates/10-zun-cni.conf.j2
- roles/docker/templates/containerd_config.toml.j2
- roles/docker/templates/overlay.conf.j2
- roles/docker/templates/zun-cni.j2
> docker: preapre zun support

- plugins/filter/address.py
> Add kolla filter plugins

- roles/docker/defaults/main.yml
- roles/docker/tasks/config-zun.yml
> docker: use fqcn for filter plugins

- README.md
- roles/traefik/defaults/main.yml
- roles/traefik/handlers/main.yml
- roles/traefik/meta/main.yml
- roles/traefik/tasks/config.yml
- roles/traefik/tasks/main.yml
- roles/traefik/tasks/service.yml
- roles/traefik/templates/docker-compose.yml.j2
- roles/traefik/templates/traefik.yml.j2
> Add traefik role

- roles/netbox/defaults/main.yml
- roles/netbox/tasks/service.yml
- roles/netbox/templates/configuration.py.j2
- roles/netbox/templates/docker-compose.yml.j2
- roles/netbox/templates/env/netbox.env.j2
- roles/netbox/templates/gunicorn_config.py.j2
- roles/traefik/defaults/main.yml
- roles/traefik/tasks/service.yml
- roles/traefik/templates/docker-compose.yml.j2
- roles/traefik/templates/traefik.yml.j2
> netbox: add traefik integration

- roles/netbox/templates/gunicorn_config.py.j2
> netbox: use endif

- roles/traefik/templates/docker-compose.yml.j2
> traefik: add missing external network

- roles/traefik/defaults/main.yml
- roles/traefik/tasks/config.yml
- roles/traefik/templates/docker-compose.yml.j2
- roles/traefik/templates/traefik.yml.j2
> traefik: support certificates

- roles/netbox/defaults/main.yml
- roles/netbox/templates/docker-compose.yml.j2
> netbox: add netbox_traefik_host

- roles/netbox/templates/docker-compose.yml.j2
> netbox: add traefik https labels

- roles/traefik/defaults/main.yml
- roles/traefik/tasks/config.yml
- roles/traefik/templates/docker-compose.yml.j2
- roles/traefik/templates/traefik.env.j
> traefik: add env file

- roles/manager/templates/wrapper/osism-update-manager.j2
> manager: sync osism-update-manager

- roles/netbox/templates/initializers/device_roles.yml.j2
- roles/netbox/templates/initializers/prefix_vlan_roles.yml.j2
> netbox: rework device roles and vlan roles

- roles/netbox/templates/initializers/device_roles.yml.j2
> netbox: add more roles

- roles/netbox/defaults/main.yml
> netbox: add netbox_dns plugin

- roles/falco/handlers/main.yml
- roles/falco/tasks/install-Debian.yml
- roles/falco/tasks/main.yml
- Use the ansible.builtin.tasks in the ansible-collection-services/roles/falco Repo
- This is partly from the github issue: osism/issues#63
> Use ansible builtin tasks

- roles/manager/defaults/main.yml
- roles/manager/tasks/config-postgres.yml
- roles/manager/tasks/config.yml
- roles/manager/tasks/initialize.yml
- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/env/ansible.env.j2
- roles/manager/templates/env/awx.env.j2
> manager: *_enable -> enable_*

- roles/manager/tasks/config-celery.yml
- roles/manager/tasks/config.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: add watchdog service

- roles/traefik/templates/certificates.yml.j2
> traefik: support default certificate

- roles/netbox/templates/initializers/prefix_vlan_roles.yml.j2
> netbox: add internal prefix/vlan role

- roles/netbox/templates/initializers/tags.yml.j2
> netbox: add managed-by tags

- roles/netbox/templates/initializers/tags.yml.j2
> netbox: add managed-by-osism tag

- roles/netbox/templates/initializers/prefix_vlan_roles.yml.j2
> netbox: add more vlan/prefix roles

- roles/netbox/defaults/main.yml
- roles/netbox/templates/initializers/custom_fields.yml.yml.j2
> netbox: add custom field device state

- roles/netbox/templates/initializers/custom_fields.yml.yml.j2
> netbox: fix name

- roles/netbox/defaults/main.yml
> netbox: disable all plugins by default

- roles/netbox/templates/docker-compose.yml.j2
- roles/nexus/defaults/main.yml
- roles/nexus/templates/docker-compose.yml.j2
- roles/nexus/templates/nexus.properties.j2
> nexus: add traefik integration

- roles/nexus/tasks/initialize.yml
> nexus: wait for /nexus-data/admin.password

- roles/nexus/tasks/config.yml
- roles/nexus/templates/docker-compose.yml.j2
- roles/nexus/templates/nexus.env.j2
> nexus: add nexus.env file

- README.md
- roles/journald/defaults/main.yml
- roles/journald/handlers/main.yml
- roles/journald/meta/main.yml
- roles/journald/tasks/main.yml
- roles/journald/templates/journald.conf.j2
> Add journald role

- roles/journald/tasks/main.yml
> journald: copy -> template

- roles/journald/defaults/main.yml
> journald: fix system name

- roles/manager/defaults/main.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: add osism-netbox service

- roles/manager/templates/docker-compose.yml.j2
> manager: add NETBOX_* to osism-netbox service

- roles/manager/templates/docker-compose.yml.j2
> manager: use osism worker for netbox worker service

- roles/manager/templates/wrapper/osism-update-manager.j2
> manager: enforce the installation of the osism.services collection

- roles/nexus/defaults/main.yml
- roles/nexus/tasks/service.yml
- roles/nexus/templates/docker-compose.yml.j2
> nexus: improve traefik integration

- roles/nexus/templates/nexus.env.j2
- roles/nexus/templates/nexus.properties.j2
> nexus: add nexus_traefik_path_prefix to templates

- roles/nexus/defaults/main.yml
- roles/nexus/tasks/call-script.yml
- roles/nexus/tasks/initialize.yml
> nexus: add http proxy support & set the admin password

- roles/nexus/tasks/initialize.yml
> nexus: change _ to -

- roles/nexus/defaults/main.yml
- roles/nexus/tasks/call-script.yml
- roles/nexus/tasks/initialize.yml
- roles/nexus/templates/docker-compose.yml.j2
- roles/nexus/templates/nexus.env.j2
- roles/nexus/templates/nexus.properties.j2
> nexus: import provision scripts first

- roles/nexus/README.md
- roles/nexus/defaults/main.yml
- roles/nexus/files/create_repos_from_list.groovy
- roles/nexus/files/setup_http_proxy.groovy
- roles/nexus/files/setup_realms.groovy
- roles/nexus/files/update_admin_password.groovy
- roles/nexus/tasks/call-script.yml
- roles/nexus/tasks/declare-script.yml
- roles/nexus/tasks/initialize.yml
* add some groovy scripts
* remove redundant tasks
* wait for the API
> nexus: overall improvements

- roles/phpmyadmin/defaults/main.yml
- roles/phpmyadmin/handlers/main.yml
- roles/phpmyadmin/tasks/main.yml
- roles/phpmyadmin/templates/docker-compose.yml.j2
> phpmyadmin: add traefik integration

- roles/manager/defaults/main.yml
- roles/manager/tasks/service.yml
- roles/manager/templates/docker-compose.yml.j2
- roles/phpmyadmin/templates/docker-compose.yml.j2
> manager enable traefik/ara-server integration

- molecule/default/molecule.yml
- molecule/delegated/collections.yml
- molecule/delegated/molecule.yml
- roles/clamav/tasks/initialize.yml
- roles/clamav/tasks/main.yml
> clamav: add init tasks

- roles/adminer/defaults/main.yml
- roles/auditd/defaults/main.yml
- roles/cephclient/defaults/main.yml
- roles/falco/defaults/main.yml
- roles/frr/defaults/main.yml
- roles/homer/defaults/main.yml
- roles/jenkins/defaults/main.yml
- roles/keycloak/defaults/main.yml
- roles/manager/defaults/main.yml
- roles/netbox/defaults/main.yml
- roles/nexus/defaults/main.yml
- roles/openldap/defaults/main.yml
- roles/openstack_health_monitor/defaults/main.yml
- roles/openstackclient/defaults/main.yml
- roles/patchman/defaults/main.yml
- roles/phpmyadmin/defaults/main.yml
- roles/rundeck/defaults/main.yml
- roles/traefik/defaults/main.yml
- roles/virtualbmc/defaults/main.yml
> Cleanup the defaults

- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/wrapper/osism.j2
> manager: add osismclient

- roles/manager/templates/docker-compose.yml.j2
> manager: fix typo

- roles/netbox/defaults/main.yml
- roles/netbox/templates/configuration.py.j2
> netbox: add plugins configuration

- roles/docker/defaults/main.yml
> docker: use opa 0.8

- .github/workflows/check-yaml-syntax.yml
- .github/workflows/test-role-auditd.yml
- .github/workflows/test-role-chrony.yml
- .github/workflows/test-role-cockpit.yml
- .github/workflows/test-role-fail2ban.yml
- .github/workflows/test-role-hddtemp.yml
- .github/workflows/test-role-netdata.yml
- .github/workflows/test-role-rng.yml
- .github/workflows/test-role-rsyslog.yml
- .github/workflows/test-role-smartd.yml
- .github/workflows/test-role-tailscale.yml
> github: run branch builds on main only

- roles/manager/defaults/main.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: add api service

- roles/manager/templates/docker-compose.yml.j2
- roles/netbox/templates/docker-compose.yml.j2
- roles/nexus/templates/docker-compose.yml.j2
- roles/phpmyadmin/templates/docker-compose.yml.j2
> traefik: redirect http to https

- roles/netbox/defaults/main.yml
- roles/netbox/templates/env/netbox.env.j2
> netbox: Add LDAP configuration variables

- roles/netbox/defaults/main.yml
- roles/netbox/templates/env/netbox.env.j2
> netbox: Add missing LDAP variables

- README.md
> README: fix broken table

- roles/netbox/templates/initializers/object_permissions.yml.j2
> Netbox: Add generic permission/group to view all objects

- README.md
- roles/dnsdist/defaults/main.yml
- roles/dnsdist/handlers/main.yml
- roles/dnsdist/meta/main.yml
- roles/dnsdist/tasks/config.yml
- roles/dnsdist/tasks/main.yml
- roles/dnsdist/tasks/service.yml
- roles/dnsdist/templates/dnsdist.conf.j2
- roles/dnsdist/templates/docker-compose.yml.j2
- roles/virtualbmc/defaults/main.yml
> Add dnsdist role

- roles/netbox/templates/configuration.py.j2
- roles/netbox/templates/env/netbox.env.j2
Netbox: Add remote auth switch to configuration.py
Netbox: Fix template file netbox.env.j2
> Netbox: fix template file netbox.env.j2 and add remote auth switch to configuration.py

- .github/workflows/test-role-auditd.yml
- .github/workflows/test-role-chrony.yml
- .github/workflows/test-role-clamav.yml
- .github/workflows/test-role-cockpit.yml
- .github/workflows/test-role-fail2ban.yml
- .github/workflows/test-role-frr.yml
- .github/workflows/test-role-hddtemp.yml
- .github/workflows/test-role-journald.yml
- .github/workflows/test-role-lldpd.yml
- .github/workflows/test-role-netdata.yml
- .github/workflows/test-role-rng.yml
- .github/workflows/test-role-rsyslog.yml
- .github/workflows/test-role-smartd.yml
- .github/workflows/test-role-tailscale.yml
> github: use ansible v5.2.0

- roles/manager/defaults/main.yml
- roles/manager/tasks/config.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: add state directory

- roles/netbox/templates/initializers/custom_fields.yml.j2
> netbox: add configuration_template custom field

- roles/manager/templates/docker-compose.yml.j2
> manager: add state directory to the ansible services

- roles/netbox/templates/initializers/custom_fields.yml.j2
> netbox: add deployment_playbook custom field

- roles/manager/templates/docker-compose.yml.j2
> manager: remove --reload parameter from uvicorn

- roles/manager/defaults/main.yml
- roles/manager/templates/env/ansible.env.j2
> manager: add manager_environment_extra parameter

- roles/manager/defaults/main.yml
- roles/manager/tasks/config-wrapper.yml
> manager: wrapper_scripts -> manager_wrapper_scripts

- roles/openstackclient/templates/docker-compose.yml.j2
Bindmount the list of certificates from the host.
> Add TLS support for openstackclient container

- roles/netbox/templates/initializers/tags.yml.j2
> netbox: add network operating system tags

- roles/bird/handlers/main.yml
- roles/bird/tasks/install-Debian.yml
- roles/bird/tasks/main.yml
Used ansible.builtin.tasks
This is partly from the github issue: issues#63.
> Ansible builtin:

- roles/netbox/templates/initializers/custom_fields.yml.j2
> netbox: add deployment_type + device_type

- roles/netbox/templates/initializers/custom_fields.yml.j2
- roles/netbox/templates/initializers/tags.yml.j2
Revert e7dc496bffc494c39c363d50f03fc022c777d4a7.
> netbox: add deploy_parameters

- roles/manager/tasks/config-netbox.yml
- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/env/ansible.env.j2
- roles/manager/templates/env/netbox.env.j2
> manager: add separate netbox.env file

- roles/manager/templates/docker-compose.yml.j2
> manager: merge env_file parameters

- roles/traefik/tasks/config.yml
> traefik: do not leak the private keys

- README.md
- roles/cgit/defaults/main.yml
- roles/cgit/handlers/main.yml
- roles/cgit/meta/main.yml
- roles/cgit/tasks/config.yml
- roles/cgit/tasks/main.yml
- roles/cgit/tasks/service.yml
- roles/cgit/templates/cgitrc.j2
- roles/cgit/templates/docker-compose.yml.j2
- roles/cgit/templates/httpd-cgit.conf.j2
> Add cgit role

- roles/homer/templates/config.yml.j2
> Add target: _blank to all homer links

- roles/netbox/templates/initializers/device_roles.yml.j2
> netbox: add more device roles

- roles/netbox/templates/initializers/device_roles.yml.j2
> netbox: add other & power device roles

- roles/netbox/templates/initializers/custom_fields.yml.j2
To save the introspection state of a system
> netbox: add custom field introspection_state

- roles/manager/templates/docker-compose.yml.j2
> manager: use the service command for flower, beat + watchdog

- roles/manager/templates/docker-compose.yml.j2
> manager: use osism service api to start the api service

- roles/manager/defaults/main.yml
- roles/manager/tasks/config-celery.yml
- roles/manager/templates/celery/listener.conf.j2
- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/env/listener.env.j2
> manager: use listener.env file

- roles/manager/templates/docker-compose.yml.j2
> manager: add netbox env to the listener service

- roles/netbox/templates/initializers/custom_fields.yml.j2
> netbox: provisioning_state -> -provision_state

- roles/netbox/templates/initializers/custom_fields.yml.j2
> netbox: add network_interface_name custom field

- roles/manager/defaults/main.yml
- roles/manager/tasks/config-celery.yml
- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/env/openstack.env.j2
> manager: add openstack worker

- roles/netbox/templates/initializers/custom_fields.yml.j2
> netbox: add deployment_state custom field

- roles/manager/tasks/config-celery.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: add conductor service

- roles/cephclient/defaults/main.yml
> cephclient: use pacific

- roles/openstackclient/defaults/main.yml
> openstackclient: use xena

- roles/homer/defaults/main.yml
- roles/homer/tasks/main.yml
- roles/homer/templates/docker-compose.yml.j2
> Add option to run homer behind traefik

- roles/manager/templates/docker-compose.yml.j2
> Change path to host for Ara-server

- roles/cgit/templates/docker-compose.yml.j2
- roles/keycloak/templates/docker-compose.yml.j2
- roles/manager/templates/docker-compose.yml.j2
- roles/netbox/templates/docker-compose.yml.j2
- roles/nexus/templates/docker-compose.yml.j2
- roles/phpmyadmin/templates/docker-compose.yml.j2
- Changed the path prefixes to host
- refactor the traefik.http....loadbalancer variable to ...-secure.loadbalancer
- This closes osism/issues#114
> Change path prefix to host

- roles/manager/templates/docker-compose.yml.j2
- add parameters to make flower accessible via traefik
- this closes issue#581
> manager: make flower accessible via traefik

- roles/manager/defaults/main.yml
> Set default flower_traefik to false

- roles/netbox/defaults/main.yml
- roles/netbox/templates/env/netbox.env.j2
> netbox: add netbox_extra to support custom parameters in netbox.env

- roles/patchman/defaults/main.yml
- roles/patchman/handlers/main.yml
- roles/patchman/tasks/main.yml
- roles/patchman/templates/docker-compose.yml.j2
- roles/patchman_client/tasks/update.yml
> Add option to run patchman behind traefik

- roles/homer/templates/config.yml.j2
- make that unused service dashboards not be visible
- This closes issues#546
> Homer: Make unused dashboards unvisible

- roles/patchman/defaults/main.yml
- roles/patchman/tasks/update.yml
> patchman: use uri to wait for the patchman service

- roles/patchman/defaults/main.yml
> patchman: use versioned image

- roles/openstack_health_monitor/defaults/main.yml
> openstack_health_monitor: use v3.0.0

- roles/zuul/defaults/main.yml
> Update zuul to 5.2.2

- roles/docker/defaults/main.yml
> docker: use single ticks for version arguments

- roles/zuul/files/builder-logging.conf
> Fix logging path in zuul role

- roles/manager/tasks/config-celery.yml
> manager: fix "Check for conductor.yml"

- roles/zuul/defaults/main.yml
> Update zuul and nodepool to 6.0.0

- roles/nexus/tasks/call-script.yml
> typo in variable call_script_nexus_url for non traefik

- roles/tang/README.rst
- roles/tang/defaults/main.yml
- roles/tang/handlers/main.yml
- roles/tang/meta/main.yml
- roles/tang/tasks/create-extraconfig.yml
- roles/tang/tasks/install-Debian.yml
- roles/tang/tasks/install-RedHat.yml
- roles/tang/tasks/main.yml
- roles/tang/templates/tangd.socket.conf.j2
- roles/tang/vars/Debian.yml
- roles/tang/vars/Redhat.yml
tang service is the server component which is needed
by network bound disk encryption
Signed-off-by: Mathias Fechner <fechner@osism.tech>
> Add tang service

- doc/source/index.rst
> index.rst: Add the roles to the file for documentation

- roles/manager/templates/wrapper/osism-update-manager.j2
> manager: enable updates via seed image

- roles/traefik/defaults/main.yml
- roles/traefik/templates/traefik.yml.j2
> traefik: make logging level configurable

- roles/manager/templates/wrapper/osism-update-manager.j2
> manager: fix syntax issue in osism-update-manager

- roles/manager/templates/docker-compose.yml.j2
> manager: add ansible configurations to the osismclient service

- roles/zuul/tasks/main.yml
> Change the place of the become condition

- roles/lldpd/README.rst
> Lldpd: Add documentation for the role

- roles/tang/README.rst
> Tang: Add description to the documentation

- .zuul.yaml
> Add default-branch to zuul config

- roles/zuul/defaults/main.yml
- roles/zuul/templates/docker-compose.yaml.j2
Signed-off-by: Tim Beermann <beermann@osism.tech>
> made container image names identical to other repositories

- roles/virtualbmc/README.rst
> Virtualbmc: Add documentation for the role

- roles/traefik/README.rst
> Traefik: Add documentation for the role

- roles/smartd/README.rst
> Smartd: Add documentation for the role

- roles/rsyslog/README.rst
> Rsyslog: Add documentation for the role

- roles/rng/README.rst
> Rng: Add documentation for the role

- roles/phpmyadmin/README.rst
> Phpmyadmin: Add documentation for the role

- roles/docker/README.rst
> Docker: Add documentation for the role

- roles/cephclient/README.rst
> Cephclient: Add documentation for the role

- roles/bird/README.rst
> Bird: Add documentation for the role

- roles/auditd/README.rst
> Auditd: Add documentation for the role

- roles/patchman/README.rst
> Patchman: Add documentation for the role

- roles/openstackclient/README.rst
> Openstackclient: Add documentation for the role

- roles/openstack_health_monitor/README.rst
> Openstack_health_monitor: Add documentation for the role

- roles/openldap/README.rst
> Openldap: Add documentation for the role

- roles/nexus/README.rst
> Nexus: Add documentation for the role

- roles/netdata/README.rst
> Netdata: Add documentation for the role

- roles/netbox/README.rst
> Netbox: Add documentation for the role

- roles/minikube/README.rst
> Minikube: Add documentation for the role

- roles/chrony/README.rst
> Chrony: Add documentation for the role

- roles/manager/README.rst
> Manager: Add documentation for the role

- roles/keycloak/README.rst
> Keycloak: Add documentation for the role

- roles/journald/README.rst
> Journald: Add documentation for the role

- roles/jenkins/README.rst
> Jenkins: Add documentation for the role

- roles/homer/README.rst
> Homer: Add documentation for the role

- roles/hddtemp/README.rst
> Hddtmp: Add documentation for the role.

- roles/fail2ban/README.rst
> Fail2ban: Add documentation for the role

- roles/dnsdist/README.rst
> Dnsdist: Add documentation to the role

- roles/docker/README.rst
> Fix Docker Role Documentation indentation of the code blocks

- roles/frr/README.rst
> Frr: Add documentation for the role

- roles/falco/README.rst
> Falco: Add documentation for the role

- roles/clamav/README.rst
> Clamav: Add documentation for the role

- roles/manager/templates/env/ara-server.env.j2
- roles/manager/templates/env/ara.env.j2
According to https://github.com/ansible-community/ara/commit/e17e1c70c3868cd3e505275aa403ad3c1c0b497a
> manager: tune ara performance

- roles/manager/README.rst
- roles/manager/defaults/main.yml
- roles/manager/templates/env/netbox.env.j2
> manager: add parameter manager_enable_bifrost

- roles/manager/README.rst
- roles/manager/templates/env/conductor.env.j2
- roles/manager/templates/env/netbox.env.j2
> manager: add parameter manager_enable_ironic

- .ansible-lint
- .ansible-lint-rules/osism_fqcn_list.yaml
- roles/bird/tasks/install-Debian.yml
- roles/cgit/tasks/service.yml
- roles/clamav/tasks/initialize.yml
- roles/docker/tasks/bootstrap.yml
- roles/frr/tasks/install-Debian.yml
- roles/homer/tasks/main.yml
- roles/keycloak/tasks/service.yml
- roles/manager/tasks/initialize-vault.yml
- roles/manager/tasks/service.yml
- roles/minikube/tasks/main.yml
- roles/netbox/tasks/service.yml
- roles/nexus/tasks/service.yml
- roles/patchman/tasks/main.yml
- roles/phpmyadmin/tasks/main.yml
- roles/traefik/tasks/service.yml
> Fix Ansible-lint errors

- .github/workflows/test-role-auditd.yml
- .github/workflows/test-role-clamav.yml
- .github/workflows/test-role-fail2ban.yml
- .github/workflows/test-role-frr.yml
- .github/workflows/test-role-journald.yml
- .github/workflows/test-role-lldpd.yml
- .github/workflows/test-role-netdata.yml
- .github/workflows/test-role-rng.yml
- .github/workflows/test-role-rsyslog.yml
- .github/workflows/test-role-smartd.yml
- .github/workflows/test-role-wireguard.yml
> Enable Ubuntu 22.04 tests

- roles/keycloak/defaults/main.yml
> keycloak: pin version

- .zuul.yaml
They will be available at
https://docs.osism.tech/ansible-collection-services/
> Add job to publish docs

- README.md
> README: add link to documentation

- roles/nexus/defaults/main.yml
> nexus: use container image from quay.io

- roles/auditd/defaults/main.yml
- roles/auditd/tasks/main.yml
- roles/auditd/vars/jammy.yml
> Add new Vars for the audisp configuration for Ubuntu 22.04

- roles/auditd/templates/rules/20-neo23x0.rules.j2
> auditd: sync neo23x0 rules with upstream

- .ansible-lint
Partly osism/issues#323
Signed-off-by: Ramona Beermann <rautenberg@osism.tech>
> Refactor ansible-lint-rules for fixing the issues after Version update

- roles/docker/tasks/install-docker-Debian.yml
> docker: update the apt cache when the repository was added

- .github/workflows/test-role-wireguard.yml
> github: do not run wireguard check for all changes in molecule/delegated

- roles/cgit/templates/docker-compose.yml.j2
- roles/dnsdist/templates/docker-compose.yml.j2
- roles/nexus/templates/docker-compose.yml.j2
- roles/squid/templates/docker-compose.yml.j2
- roles/traefik/templates/docker-compose.yml.j2
- roles/zuul/templates/docker-compose.yaml.j2
> Remove docker compose version (pt. 2)

- roles/openstack_health_monitor/README.rst
- roles/openstack_health_monitor/defaults/main.yml
- roles/openstack_health_monitor/tasks/container-Debian.yml
> openstack-health-monitor: use docker-compose service

- roles/netbox/templates/nginx-unit.json.j2
> netbox: fix static share for nginx unit > 1.26

- roles/netbox/defaults/main.yml
> netbox: use version v3.3.9

- roles/netbox/tasks/config-netbox.yml
- roles/netbox/templates/nginx-unit-1.26.json.j2
> netbox: support older nginx unit versions

- roles/netbox/templates/initializers/device_roles.yml.j2
> netbox: add device role housing

- roles/zuul/files/zk-ca.sh
> Change copyright date

- roles/netdata/README.rst
- roles/netdata/defaults/main.yml
- roles/netdata/templates/netdata.conf.j2
> netdata: improve configuration

- roles/auditd/templates/rules/20-neo23x0.rules.j2
> auditd: sync rules with Neo23x0/auditd

- roles/openstackclient/templates/docker-compose.yml.j2
Co-authored-by: Arvid Requate <requate@univention.de>
> openstackclient: add REQUESTS_CA_BUNDLE env variable

- roles/manager/README.rst
- roles/manager/defaults/main.yml
- roles/manager/templates/docker-compose.yml.j2
New parameters:
* enable_beat
* enable_flower
> manager: make disablement of beat & flower service possible

- roles/manager/templates/docker-compose.yml.j2
> manager: add missing if

- roles/manager/templates/docker-compose.yml.j2
> manager: improve the readability of the docker-compose template

- roles/netbox/templates/docker-compose.yml.j2
> netbox: wait for healty redis & db services

- roles/manager/templates/docker-compose.yml.j2
> manager: wait for healty redis & db services

- roles/netbox/templates/docker-compose.yml.j2
> netbox: add missing :

- roles/dnsdist/README.rst
- roles/dnsdist/defaults/main.yml
- roles/dnsdist/templates/docker-compose.yml.j2
> dnsdist: allow multiple host bindings with dnsdist_hosts

- roles/zuul/defaults/main.yml
- roles/zuul/templates/docker-compose.yaml.j2
- roles/zuul/templates/zuul.conf.j2
- Update containers to latest upstream versions
- Add auth configuration
- Fix variable names for nodepool images
- Add zuul_user definition to role defaults
> Update zuul role

- .zuul.yaml
- Enable checks via zuul job flake8
- Partly osism/issues#397
> Python: Enable sysntax check

- roles/zuul/defaults/main.yml
Both have had a new release with version 8.2.0.
> Update zuul and nodepool versions

- roles/auditd/tasks/install-Debian.yml
- roles/bird/tasks/install-Debian.yml
- roles/cephclient/tasks/package-Debian.yml
- roles/chrony/tasks/install-Debian.yml
- roles/clamav/tasks/install-Debian.yml
- roles/containerd/tasks/install-Debian.yml
- roles/docker/tasks/install-docker-Debian.yml
- roles/fail2ban/tasks/install-Debian.yml
- roles/falco/tasks/install-Debian.yml
- roles/frr/tasks/install-Debian.yml
- roles/hddtemp/tasks/install-Debian.yml
- roles/lldpd/tasks/install-Debian.yml
- roles/manager/tasks/install-Debian.yml
- roles/minikube/tasks/main.yml
- roles/netdata/tasks/install-Debian.yml
- roles/openstackclient/tasks/package-Debian.yml
- roles/osquery/tasks/install-Debian.yml
- roles/patchman_client/tasks/install-Debian.yml
- roles/rng/tasks/install-Debian.yml
- roles/rsyslog/tasks/install-Debian.yml
- roles/smartd/tasks/install-Debian.yml
- roles/tang/tasks/install-Debian.yml
- roles/wireguard/tasks/main.yml
> Set apt lock timeout to 300 by default

- roles/cephclient/tasks/package-Debian.yml
- roles/containerd/tasks/install-Debian.yml
- roles/docker/tasks/install-docker-Debian.yml
- roles/falco/tasks/install-Debian.yml
- roles/netdata/tasks/install-Debian.yml
- roles/openstackclient/tasks/package-Debian.yml
- roles/osquery/tasks/install-Debian.yml
> Do not use apt-key on Ubuntu 22.04

- roles/falco/tasks/install-Debian.yml
> Role falco: Remove all "Wait for apt lock“ tasks

- roles/docker/tasks/install-docker-Debian.yml
> Role docker: Remove all "Wait for apt lock“ tasks

- roles/manager/README.rst
- roles/manager/defaults/main.yml
- roles/manager/tasks/config-celery.yml
- roles/manager/templates/docker-compose.yml.j2
With enable_listener it is possible to enable/disable the listener service.
> manager: add enable_listener

- roles/manager/templates/wrapper/osism-update-manager.j2
> manager: sync reconciler after an update

- roles/auditd/handlers/main.yml
Add changed when at Genrate auditd rules
> Auditd: Fix syntaxcheck in handlers

- roles/rng_tools/README.rst
- roles/rng_tools/defaults/main.yml
- roles/rng_tools/meta/main.yml
- roles/rng_tools/tasks/install-Debian.yml
- roles/rng_tools/tasks/install-RedHat.yml
- roles/rng_tools/tasks/main.yml
for a enhanced  entropy behavior for workload instances rng-tools must be enabled on nodes
> Add: rng tools

- roles/rng/README.rst
- roles/rng/defaults/main.yml
- roles/rng/meta/main.yml
- roles/rng/tasks/install-Debian.yml
- roles/rng/tasks/install-RedHat.yml
- roles/rng/tasks/main.yml
for a enhanced  entropy behavior for workload instances rng-tools must be enabled on nodes
> replace: haveged with rng tools

- roles/manager/templates/wrapper/osism-update-manager.j2
* PYTHON_EXECUTABLE
Part of osism/issues#505
> manager: make python executable configurable in update script

- roles/squid/defaults/main.yml
- registry-1.docker.io
- auth.docker.io
- production.cloudflare.docker.com
> squid: allow Docker Hub

- .ansible-lint
- roles/chrony/meta/main.yml
- roles/clamav/meta/main.yml
- roles/containerd/tasks/install-Debian.yml
- roles/docker/tasks/config.yml
- roles/docker/tasks/install-docker-Debian.yml
- roles/docker/tasks/storage.yml
- roles/hddtemp/meta/main.yml
- roles/minikube/tasks/main.yml
- roles/nexus/tasks/initialize.yml
- roles/patchman/tasks/update.yml
- roles/rng/meta/main.yml
- roles/tang/meta/main.yml
- Fix some lintingerrors after refactoring.
- Exclude only affected tasks where necessary.
- Delete not needed noqas
- Partly osism/issues#496
> Ansible-lint: Refactor rules and noqas

- roles/manager/tasks/service.yml
- roles/netbox/tasks/service.yml
> Handle service start errors via blocks (pt. 1)

- roles/manager/tasks/service.yml
- roles/netbox/tasks/service.yml
This will avoid the python docker-compose dependency.
> Use ansible.builtin.command instead of docker_compose task

- roles/auditd/templates/rules/20-neo23x0.rules.j2
> auditd: sync neo23x0 rules

- roles/docker/README.rst
- roles/docker/defaults/main.yml
- roles/docker/templates/daemon.json.j2
Leftover from the past. Is not used.
> docker: remove docker_dragonfly parameter

- roles/rsyslog/README.rst
- roles/rsyslog/defaults/main.yml
- roles/rsyslog/templates/71-additional-log-server.conf.j2
> rsyslog: make additional log server protocol configurable

- releasenotes/notes/manager-mariadb-MARIADB_AUTO_UPGRADE-7b3812dd9a8dd91c.yaml
- roles/manager/templates/env/mariadb.env.j2
> manager: set MARIADB_AUTO_UPGRADE=1

- releasenotes/notes/manager-opensearch-protocol-6899e3ff20ec511b.yaml
- roles/manager/README.rst
- roles/manager/defaults/main.yml
- roles/manager/templates/env/client.env.j2
> manager: make opensearch protocol configurable

- releasenotes/notes/manager-resource-limits-8dc65134a0738a8d.yaml
- roles/manager/defaults/main.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: allow resource limits of ansible services

- releasenotes/notes/manager-improve-wait-for-an-healthy-manager-services-fc6132d1cfeed397.yaml
- roles/manager/tasks/service.yml
Related to osism/issues#747
Related to osism/cloud-in-a-box#159
> manager: improve "Wait for an healthy manager service" task

- roles/chrony/tasks/main.yml
Closes osism/ansible-collection-services#1196
> chronyd: check if systemd-timesyncd exists

- roles/manager/handlers/main.yml
- roles/manager/tasks/service.yml
> manager: update osismclient bash completion always and at the end

- roles/manager/defaults/main.yml
Required by the "Wait for an healthy manager service" handler.
> manager: install jq

- releasenotes/notes/manager-update-wrapper-arguments-2f5ea72ac68aa8ec.yaml
- roles/manager/templates/wrapper/osism.j2
> manager: allow arguments in the osism update scripts

- roles/manager/templates/docker-compose.yml.j2
> manager: make redis stateless

- roles/falco/tasks/install-Debian.yml
cf. https://github.com/osism/issues/issues/850
> Fixing falco role

- roles/keycloak/templates/cloudnative-pg-keycloak.yml.j2
For https://github.com/SovereignCloudStack/issues/issues/507
> add missing template for cloudnative-pg

- README.md
- galaxy.yml
- roles/homer/templates/config.yml.j2
Part of https://github.com/osism/issues/issues/927
> Replace osism.github.io with osism.tech

- .zuul.yaml
cf. https://github.com/osism/issues/issues/957
> Fixing zuul.yaml regex

- molecule/delegated/prepare/adminer.yml
- molecule/delegated/prepare/cephclient.yml
- molecule/delegated/prepare/cgit.yml
- molecule/delegated/prepare/dnsdist.yml
- molecule/delegated/prepare/homer.yml
- molecule/delegated/prepare/manager.yml
- molecule/delegated/prepare/metering.yml
- molecule/delegated/prepare/netbox.yml
- molecule/delegated/prepare/nexus.yml
- molecule/delegated/prepare/openstack_health_monitor.yml
- molecule/delegated/prepare/openstackclient.yml
- molecule/delegated/prepare/phpmyadmin.yml
- molecule/delegated/prepare/scaphandre.yml
- molecule/delegated/prepare/squid.yml
- molecule/delegated/prepare/thanos_sidecar.yml
- molecule/delegated/prepare/traefik.yml
- molecule/delegated/prepare/virtualbmc.yml
- molecule/delegated/prepare/zuul.yml
This is necessary for the fact files of osism.services.docker to work correctly.
> molecule: install missing packages in venv

- roles/openstackclient/handlers/main.yml
- roles/openstackclient/tasks/container-Debian-family.yml
- roles/openstackclient/tasks/container-RedHat-family.yml
> openstackclient: wait until the managed service is active

- roles/manager/handlers/main.yml
- roles/manager/tasks/service.yml
> manager: wait until the managed service is active

- roles/adminer/handlers/main.yml
- roles/adminer/tasks/main.yml
> adminer: wait until the managed service is active

- roles/cgit/handlers/main.yml
- roles/cgit/tasks/service.yml
> cgit: wait until the managed service is active

- roles/dnsdist/handlers/main.yml
- roles/dnsdist/tasks/service.yml
> dnsdist: wait until the managed service is active

- roles/homer/handlers/main.yml
- roles/homer/tasks/main.yml
> homer: wait until the managed service is active

- roles/phpmyadmin/handlers/main.yml
- roles/phpmyadmin/tasks/main.yml
> phpmyadmin: wait until the managed service is active

- roles/scaphandre/handlers/main.yml
- roles/scaphandre/tasks/service.yml
> scaphandre: wait until the managed service is active

- roles/virtualbmc/handlers/main.yml
- roles/virtualbmc/tasks/service.yml
> virtualbmc: wait until the managed service is active

- roles/nexus/handlers/main.yml
- roles/nexus/tasks/service.yml
> nexus: wait until the managed service is active

- roles/netbox/handlers/main.yml
- roles/netbox/tasks/service.yml
> netbox: wait until the managed service is active

- molecule/delegated/prepare/docker.yml
- molecule/delegated/tests/docker/debian.py
- molecule/delegated/tests/docker/redhat.py
- roles/docker/tasks/main.yml
- roles/docker/vars/Debian-family.yml
- roles/docker/vars/RedHat-family.yml
> docker: use prefix variables for OS specific defaults

- molecule/delegated/tests/containerd/debian.py
- roles/containerd/tasks/main.yml
- roles/containerd/vars/CentOS-dist.yml
- roles/containerd/vars/Debian-dist.yml
- roles/containerd/vars/Ubuntu-dist.yml
> containerd: use prefix variables for OS specific defaults

- roles/manager/templates/wrapper/osism-update-docker.j2
Part of osism/issues#759
Related to 79e38461b69465956779eedd026c6edc8cf78b02
> manager: also get versions in the osism-update-docker script

- roles/manager/templates/wrapper/osism-update-docker.j2
Part of osism/issues#978
Related to 965550532c269530590fd118869d4b8fc5abe5a9
> manager: also detect use of vault in the osism-update-docker script

- .zuul.yaml
> zuul: add testing on Ubuntu 24.04

- molecule/delegated/tests/chrony/debian.py
- molecule/delegated/tests/fail2ban.py
cf. https://github.com/osism/issues/issues/1004
>  Fix failed Ubuntu 24.04 tests

- roles/manager/tasks/config-scripts.yml
- roles/manager/tasks/config.yml
- roles/manager/templates/scripts/osism-include.j2
- roles/manager/vars/scripts.yml
These scripts combine a few things. They are based on the scripts in the osism/testbed repository.
> manager: support scripts

- roles/traefik/defaults/main.yml
- roles/traefik/templates/traefik.yml.j2
Extra configuration can be set via traefik_configuration_extra.
> traefik: make extra configuration possible

- molecule/delegated/tests/netdata/debian.py
- molecule/delegated/tests/netdata/redhat.py
- molecule/delegated/vars/netdata.yml
- roles/netdata/defaults/main.yml
> netdata: use new official repository

- roles/manager/templates/wrapper/osism-update-manager.j2
> manager: warn when Ansible is installed

- molecule/delegated/tests/netdata/redhat.py
- roles/netdata/tasks/install-Debian-family.yml
- roles/netdata/tasks/install-RedHat-family.yml
- roles/netdata/tasks/main.yml
* remove duplicate tasks
* remove tasks not longer necessary
> netdata: cleanup

- molecule/delegated/prepare.yml
- molecule/delegated/prepare/adminer.yml
- molecule/delegated/prepare/cephclient.yml
- molecule/delegated/prepare/cgit.yml
- molecule/delegated/prepare/dnsdist.yml
- molecule/delegated/prepare/docker.yml
- molecule/delegated/prepare/homer.yml
- molecule/delegated/prepare/manager.yml
- molecule/delegated/prepare/metering.yml
- molecule/delegated/prepare/netbox.yml
- molecule/delegated/prepare/nexus.yml
- molecule/delegated/prepare/openstack_health_monitor.yml
- molecule/delegated/prepare/openstackclient.yml
- molecule/delegated/prepare/phpmyadmin.yml
- molecule/delegated/prepare/scaphandre.yml
- molecule/delegated/prepare/squid.yml
- molecule/delegated/prepare/thanos_sidecar.yml
- molecule/delegated/prepare/traefik.yml
- molecule/delegated/prepare/virtualbmc.yml
- molecule/delegated/prepare/zuul.yml
Related to 7dd24abaadd657db69a4a5e15c47131591a588d9
> molecule: always install docker & netaddr

- roles/kubernetes_monitoring/README.rst
- roles/kubernetes_monitoring/defaults/main.yml
- roles/kubernetes_monitoring/meta/main.yml
- roles/kubernetes_monitoring/tasks/config-kubernetes-monitoring.yml
- roles/kubernetes_monitoring/tasks/config-openstack-exporter.yml
- roles/kubernetes_monitoring/tasks/config.yml
- roles/kubernetes_monitoring/tasks/deploy-kubernetes-monitoring.yml
- roles/kubernetes_monitoring/tasks/deploy-openstack-exporter.yml
- roles/kubernetes_monitoring/tasks/main.yml
- roles/kubernetes_monitoring/tasks/namespace.yml
- roles/kubernetes_monitoring/templates/kubernetes_monitoring.yml.j2
- roles/kubernetes_monitoring/templates/openstack_exporter.yml.j2
Related PRs
- https://github.com/osism/ansible-playbooks/pull/420
- https://github.com/osism/defaults/pull/181
SCS issue: https://github.com/SovereignCloudStack/issues/issues/576
> Add kubernetes monitoring role

- roles/rook/defaults/main.yml
- roles/rook/tasks/wait-for-cluster-deleted.yml
- roles/rook/tasks/wait-for-cluster.yml
* add newlines in defaults for better readability
* check more often in the wait tasks
* improve task name of the wait tasks
> rook: improve some nits

- roles/netbox/defaults/main.yml
- roles/netbox/tasks/install-Debian-family.yml
- roles/netbox/tasks/install-RedHat-family.yml
- roles/netbox/tasks/main.yml
Required by the new "Wait for an healthy netbox service" handler.
> netbox: ensure that jq is installed

- roles/traefik/templates/traefik.yml.j2
> traefik: do not check for new versions

- roles/manager/defaults/main.yml
- roles/manager/tasks/config.yml
- roles/manager/templates/docker-compose.yml.j2
> manager: add data directory for osismclient

- molecule/delegated/vars/docker.yml
- roles/docker/defaults/main.yml
- roles/docker/tasks/main.yml
- roles/docker/tasks/storage-block.yml
- roles/docker/tasks/storage-zram.yml
Intended for use in CI and testing.
> docker: add support for zram devices

- roles/rook/tasks/change-labels.yml
- roles/rook/tasks/cleanup-labels.yml
- roles/rook/tasks/cleanup.yml
Fixes [osism/issues#1084](https://github.com/osism/issues/issues/1084)
> Add task to remove and change labels regarding Rook

- molecule/delegated/vars/netbox.yml
- roles/netbox/templates/docker-compose.yml.j2
- roles/netbox/vars/main.yml
> netbox: make start_period configurable

- roles/rook/defaults/main.yml
- roles/rook_operator/defaults/main.yml
Related to 06bb1a3e209c70f5cbc6959fcf47b396f471ae98.
> Fix handling of rook versions

- roles/netbox/defaults/main.yml
- roles/netbox/handlers/main.yml
- roles/netbox/tasks/restart-service.yml
- roles/netbox/tasks/service.yml
> netbox: upgrade postgres database

- molecule/delegated/prepare/chrony.yml
- molecule/delegated/tests/chrony/main.py
- Enhance CI tests to validate chrony server reachability.
> chrony: Enhance CI tests

- molecule/delegated/tests/phpmyadmin.py
- Check the reachability of phpMyAdmin using curl.
> phpmyadmin: Enhance CI tests

- roles/wireguard/tasks/main.yml
> wireguard: ensure that iptables is installed

- roles/frr/defaults/main.yml
- roles/frr/templates/daemons.j2
frr_enable_bgpd: "yes"
frr_enable_bfdd: "no"
> frr: allow to enable/disable the bgpd/bfdd services

- molecule/delegated/tests/adminer.py
> adminer: Enhance CI tests

- molecule/delegated/tests/auditd.py
> auditd: Enhance CI tests

- molecule/delegated/tests/cgit.py
> cgit: Enhance CI tests

- molecule/delegated/tests/cephclient/main.py
> cephclient: Improve CI tests

- roles/docker/tasks/install-docker-Debian-family.yml
> docker: fix python3-docker installation @ Ubuntu 24.04

- molecule/delegated/tests/dnsdist.py
> dnsdist: Enhance CI tests

- molecule/delegated/tests/clamav/main.py
> clamav: Enhance CI tests

- molecule/delegated/tests/lldpd.py
> lldpd: Enhance CI tests

- molecule/delegated/tests/openstackclient/main.py
> openstackclient: Enhance CI tests

- molecule/delegated/tests/fail2ban.py
- roles/fail2ban/tasks/main.yml
- roles/fail2ban/templates/sshd.conf.j2
> fail2ban: Enhance CI tests

- molecule/delegated/tests/frr.py
- molecule/delegated/vars/frr.yml
- roles/frr/templates/frr_test.conf.j2
> frr: Enhance CI tests

- molecule/delegated/tests/manager.py
> manager: Enhance CI tests

- molecule/delegated/tests/rsyslog.py
- roles/rsyslog/tasks/main.yml
- roles/rsyslog/templates/rsyslog.conf.j2
- roles/rsyslog/vars/CentOS-dist.yml
- roles/rsyslog/vars/Debian-dist.yml
- roles/rsyslog/vars/Ubuntu-dist.yml
> rsyslog: Enhance CI tests

- molecule/delegated/tests/virtualbmc.py
Related issue: https://github.com/osism/issues/issues/1132
> virtualbmc: Enhance CI tests

- molecule/delegated/tests/zabbix_agent.py
> zabbix_agent: Enhance CI tests

- molecule/delegated/tests/traefik.py
> traefik: Enhance CI tests

- molecule/delegated/tests/squid.py
- test proxy functionality
- check configuration and status
> squid: Enhance CI tests

- molecule/delegated/tests/docker/main.py
> docker: Enhance CI tests

- molecule/delegated/tests/thanos_sidecar.py
> thanos_sidecar: Enhance CI tests

- molecule/delegated/tests/tang.py
> tang: Enhance CI tests

- roles/teleport/defaults/main.yml
- roles/teleport/templates/teleport.yaml.j2
* add teleport_ca_pin parameter
* add teleport_label node parameter
* use join_params instead auf auth_token
> teleport: overall improvements

- .zuul.yaml
- molecule/delegated/tests/teleport/debian.py
- molecule/delegated/tests/teleport/main.py
- molecule/delegated/tests/teleport/redhat.py
- roles/teleport/defaults/main.yml
- roles/teleport/tasks/install-Debian-family.yml
- roles/teleport/tasks/install-RedHat-family.yml
Adds CentOS support and more meaningful tests
> teleport: Add Centos support

- roles/frr/defaults/main.yml
- roles/frr/templates/daemons.j2
* frr_options_bgpd
* frr_options_bfdd
> frr: make bgpd & bfdd options configurable

- roles/frr/defaults/main.yml
- roles/frr/handlers/main.yml
- roles/frr/tasks/main.yml
- Allow the user to decide to automatically restart frr after configuration changes or not
- Allow the user to override the location of the config files (this is useful with the previous enhancements to dryrun, compare/inspect and test structural changes)
> Give more control over frr config

- roles/rook/defaults/main.yml
- roles/rook/tasks/deploy.yml
- roles/rook/templates/secret-keystone-user.yml.j2
Initial adaption of the Keystone/Swift integration in Rook.
Fixes [osism/issues/issues/1027](https://github.com/osism/issues/issues/1027)
> rook: Add Keystone and Swift integration

- roles/homer/defaults/main.yml
- roles/homer/templates/config.yml.j2
> homer: add cgit dashboard

- roles/homer/defaults/main.yml
- roles/homer/templates/config.yml.j2
> homer: add skyline dashboard

- roles/netbox/templates/initializers/device_roles.yml.j2
> netbox: add DPU device role

- roles/netbox/templates/initializers/custom_fields.yml.j2
Add:
* out-of-band-address
* out-of-band-port
Remove:
* deployment_enabled
* ironic_enabled
* configuration_template
* device_state
* device_transition
* device_type
* deployment_type
* deployment_state
* introspection_state
* network_interface_name
* ironic_state
Part of https://github.com/osism/issues/issues/1228
> Update custom fields in netbox

- .zuul.yaml
Related to 5c2fc8fbd9498f11832d45ecb85b31771974a023
> zuul: fix wrong secret

- roles/manager/defaults/main.yml
- roles/manager/tasks/config-netbox.yml
- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/env/conductor.env.j2
Add python-osism netbox parameter
* OSISM_CONDUCTOR_NETBOX_FILTER_LIST
* NETBOX_SECONDARIES
to the manager role
> Add osism netbox parameter to manager role

- roles/manager/defaults/main.yml
- roles/manager/tasks/config-netbox.yml
- roles/manager/templates/docker-compose.yml.j2
- roles/manager/templates/env/inventory-reconciler.env.j2
Requried to configure the netbox -> inventory sync.
> manager: add inventory-reconciler env file

- roles/manager/defaults/main.yml
- roles/manager/templates/env/inventory-reconciler.env.j2
With this parameter it's possible to filter devices that should be included in the inventory.
> manager: add netbox_filter_inventory parameter

- roles/manager/tasks/main.yml
- roles/manager/tasks/verify-versions.yml
- roles/manager/templates/check-service-manager-versions.sh.j2
- Add Jinja2 template for dynamic version checking script
- Include conditional execution based on service settings
- Verify all containers match expected versions after deployment
- Skip verification when manual start or restart disabled
AI-assisted: Claude Code
> manager: add container version verification system
