osism/ansible-collection-services

molecule/auditd/prepare.yml
molecule/osquery/prepare.yml
molecule/rsyslog/prepare.yml

Upgrade + reboot only necessary if an ansible role builds
a kernel module via DKMS.

molecule: cleanup prepare playbooks

---

roles/docker/defaults/main.yml

docker: use version 20.10.0

---

roles/auditd/tasks/main.yml

auditd: do not remove osas-auditd-rhel7.rules

---

roles/zabbix_agent/tasks/install-Debian.yml
roles/zabbix_agent/tasks/main.yml

zabbix_start: start/enable the service after the config tasks

---

roles/zabbix_agent/tasks/cleanup-Debian.yml

zabbix_agent: remove old zabbix_agentd.conf.d directory

---

roles/zabbix_agent/defaults/main.yml
roles/zabbix_agent/templates/zabbix_agent2.conf.j2

zabbix_agent: on zabbix server nodes allow the zabbix server network

---

roles/zabbix_agent/tasks/install-Debian.yml

zabbix_agent: add missing service to handler name

---

roles/docker/defaults/main.yml

docker: use version 20.10.6

---

roles/manager/templates/docker-compose.yml.j2

manager: fix path used for the inventory_reconciler volume

---

roles/manager/templates/docker-compose.yml.j2

manager: ansible services depend on inventory_reconciler service

---

roles/jenkins/defaults/main.yml

jenkins: add missing jenkins_configuration_directory parameter

---

roles/jenkins/defaults/main.yml

jenkins: fix wrong docker registry

---

roles/manager/defaults/main.yml

manager: use eventclass sync as default for ara

---

roles/manager/tasks/config-ara.yml

manager: make mariadb.env file optional

---

roles/openldap/templates/env/openldap.env.j2

openldap: Use an empty list by default for SERVICE_PROVIDERS (#273)

---

roles/openldap/defaults/main.yml

Further relaxes reliance on SERVICE_PROVIDERS

openldap: bump default image tag

---

.github/templates/galaxy.yml.j2

changed osism.de to osism.tech

---

roles/patchman/templates/docker-compose.yml.j2

The initial repository import is very IO intensive and may exceed the
timeout of 30 minutes in the testbed deployment. Since the data can be
considered ephemeral, we switch to using a tmpfs volume, which reduces
the runtime to about 10 minutes.
Closes: #352

Run patchman_postgres on tmpfs volume

---

roles/manager/defaults/main.yml
roles/manager/templates/docker-compose.yml.j2

Will be required as a broker for celery in the future.

manager: always enable redis

---

roles/patchman/defaults/main.yml
roles/patchman/tasks/update.yml

If patchman_update_force is set to true an update is always
executed when the role is executed

patchman: add patchman_update_force parameter

---

roles/manager/defaults/main.yml

On manager nodes with many threads, the current default leads
to a very high number of processes.

manager: reduce number of ara-workers to 5

---

roles/traefik/defaults/main.yml
roles/traefik/tasks/config.yml
roles/traefik/templates/traefik.yml.j2

To ensure the TLS keys can be encrypted in ansible-vault the keys and
certificates are fetched from variables.

Read Traefik TLS keys and certificates from variables

---

roles/traefik/defaults/main.yml
roles/traefik/tasks/config.yml
roles/traefik/templates/docker-compose.yml.j2
roles/traefik/templates/traefik.yml.j2

- Use one dictionary for TLS certificates and key as subelements
- Fix statement in docker-compose.yml

traefik: consolidate TLS cert and key dictionary

---

roles/rundeck/tasks/config-postgres.yml
roles/rundeck/tasks/config-rundeck.yml
roles/rundeck/tasks/config.yml
roles/rundeck/tasks/main.yml
roles/rundeck/tasks/service.yml

- Use the ansible.builtin.tasks in the ansible-collection-services/roles/rundeck Repo
- This is partly from the github issue: osism/issues#63

Use ansible builtin tasks

---

roles/traefik/tasks/config.yml
roles/traefik/templates/certificates.yml.j2
roles/traefik/templates/docker-compose.yml.j2
roles/traefik/templates/traefik.yml.j2

TLS certificate files have to be configured in a dynamic configuration
file to be usable in conjuction with config options from Docker
provider.

Traefik: Add dynamic configuration for TLS certificates

---

roles/nexus/tasks/initialize.yml

The internal scripts now take over.

nexus: do not wait for the service

---

roles/netbox/defaults/main.yml

netbox: enable the osism plugin by default

---

roles/netbox/defaults/main.yml

The dictionary key `netbox_user_name` needs to be evaluated, to substitute
the variable.

Netbox: Template users initializer dictionary

---

roles/manager/templates/docker-compose.yml.j2
roles/manager/templates/env/ansible.env.j2

Make the hosts CA bundle available in manager docker containers.

Manager: Make CA bundle available in containers

---

roles/manager/templates/env/ansible.env.j2

Causes strange errors in the testbed in interaction with
the self-signed certificate from Traefik. Therefore
partial revert of d0d42c1d84dc8b194b48acda43bb348f43f67778
for the moment.

manager: remove REQUESTS_CA_BUNDLE

---

roles/chrony/defaults/main.yml
roles/chrony/templates/chrony.conf.j2

With the chrony_bindaddresses parameter it is possible to
bind Chrony to specific addresses.
This PR also removes the bindcmdaddress parameters from
the chrony.conf.j2 template as they are set to these
values by default.

chrony: add chrony_bindaddresses parameter

---

roles/keycloak/defaults/main.yml
roles/keycloak/tasks/service.yml
roles/keycloak/templates/docker-compose.yml.j2

To use Keycloak behind Traefik, a customized image of
Keycloak is required. This is necessary because the used
path keycloak must be set explicitly in various static
configuration files in the image.
The customized image is maintained in osism/container-images.
Closes #567

keycloak: add traefik integration

---

roles/netbox/templates/initializers/custom_fields.yml.j2

In this field for a device, the action/transition
that has just been performed can be recorded. E.g.
from_a_b if the device is currently in transition
from state a to state b. Or complete_a_b if the
transition from state a to state b has been completed.

netbox: add device_transition custom field

---

roles/manager/templates/docker-compose.yml.j2

The netbox parameters will be needed by python-osism in
various places in the future.

manager: add netbox parameters to the beat and osismclient services

---

roles/manager/defaults/main.yml
roles/manager/tasks/config-celery.yml
roles/manager/templates/celery/listener.conf.j2
roles/manager/templates/docker-compose.yml.j2

The listener service is available for evaluating notifications
from OpenStack.

manager: add listener service

---

roles/manager/defaults/main.yml
roles/virtualbmc/defaults/main.yml

More IP addresses are needed because the number of
services has increased.

manager: resize the manager network

---

roles/netbox/templates/initializers/custom_fields.yml.j2

Config Context is used for this purpose.

netbox: remove deployment_parameters

---

roles/netbox/templates/initializers/custom_fields.yml.j2

This field records whether a device has already
been registered in Ironic or not.

netbox: add custom field ironic_state

---

roles/netbox/templates/initializers/custom_fields.yml.j2

With those custom fields it is possible to enable/disable the
deployment and use of a device with ironic.

netbox: add ironic_enabled & deployment_enabled custom fields

---

roles/manager/defaults/main.yml

Vault is currently not yet integrated. Therefore
it should not be deployed by default at the moment.
Until now, Vault was deployed when AWX was activated.
AWX was activated by default. By removing AWX, the
default for Vault has mistakenly changed from False
to True.

manager: do not enable vault service by default

---

roles/manager/templates/wrapper/osism-update-manager.j2

With the environment variable ANSIBLE_COLLECTION_SERVICES_VERSION
the branch of osism.services to be used can now be selected.
By default the main branch is taken.
Example:
ANSIBLE_COLLECTION_SERVICES_VERSION=main osism-update-manager

manager: make the branch of the used Ansible collection configurable

---

roles/traefik/tasks/config.yml

This ensures that no private keys end up in the logs.

traefik: add no_log to the "Copy certificate cert files" task

---

roles/keycloak/defaults/main.yml

Parameter is left and is no longer needed.

keycloak: remove keycloak_for_traefik_image

---

roles/homer/templates/config.yml.j2

Spaces in front of the if/endif statements end up in the yaml file,
breaking the formatting. Move the indentation inside the {% %} block.

Fix indentation in the Homer config template

---

roles/docker/defaults/main.yml

So it is unified with osism.commons.proxy

docker: use docker_proxy_no_proxy_(extra+default)

---

.github/renovate.json
roles/docker/defaults/main.yml

- Add the docker-role to the renovate.json for auto-updating the Docker-Version
- This closes osism/issues#147

Add Docker-role to renovate for auto-update the Dockerversion

---

roles/manager/tasks/config-celery.yml

- Rename the modules to the ansible FQCN´s
- This is partly: osism/issues#165

Use the Ansible FQCN´s

---

roles/docker/tasks/bootstrap.yml
roles/docker/tasks/config-open-policy-agent.yml
roles/docker/tasks/config.yml
roles/docker/tasks/install-docker-Debian.yml
roles/docker/tasks/install-kata-Debian.yml
roles/docker/tasks/install-open-policy-agent.yml
roles/docker/tasks/service.yml
roles/docker/tasks/storage.yml

We have the become in the other roles above the task and not
below. Hence the adjustment here.

docker: move become to the top

---

roles/netbox/templates/docker-compose.yml.j2

Since the migrations are running at the initial start,
it takes some time until the service is available.
To avoid an unnecessary unhealthy state, perform the
first test only after 120 seconds.

netbox: wait 120 seconds until the first healthcheck

---

roles/cgit/templates/docker-compose.yml.j2

When you call / the directory listing is currently displayed.
The cgit runs only under /cgit. Therefore / should be rewritten
to /cgit so that the call from / works directly.

cgit: rewrite / to /cgit

---

roles/docker/defaults/main.yml
roles/docker/tasks/install-docker-Debian.yml

Make sure that the package cache is up to date so that newer Docker
versions will be available in any case.
Related to osism/issues#221

docker: update package cache

---

roles/nexus/templates/docker-compose.yml.j2

nexus: use nexus_traefik_host variable for traefik router rules

---

roles/nexus/templates/docker-compose.yml.j2

The health check needs to use the /nexus/ path to recieve a successful
http return code.

nexus: fix docker health check

---

roles/tang/tasks/create-extraconfig.yml

Change to become true to tang role systemd part that ansible is able to configure
systemd unit files
and open Port 1080 for iptables
Signed-off-by: Mathias Fechner <fechner@osism.tech>

Add become true and open fw

---

roles/tang/templates/tangd.socket.conf.j2

the default port is already defined in tang defaults
it make no sense to define it generic in template
Signed-off-by: Mathias Fechner <fechner@osism.tech>

tang: remove static port definition

---

roles/squid/templates/osism_allow_list.conf.j2

squid: fix wrong parameter name

---

roles/manager/defaults/main.yml

manager: add missing default for manager_enable_ironic

---

roles/wireguard/README.rst
roles/wireguard/defaults/main.yml
roles/wireguard/tasks/main.yml

With the wireguard_client_configuration_file parameter it is
possible to set the name of the configurtion file in the
operator home directory.

wireguard: add wireguard_client_configuration_file

---

roles/manager/templates/docker-compose.yml.j2

manager: mount environments/openstack to /etc/openstack

---

roles/netbox/tasks/config-netbox.yml

The previous patch missed one location that needs to be changed to use template.

Fix creating netbox secret files

---

roles/homer/templates/config.yml.j2

closes #893
The color scheme itself is not very ideal. Homer does not offer a very flexible way of changing every individual compoenent.
Therefore sticking to original color scheme in light mode.
Signed-off-by: Larissa Stoffers <stoffers@osism.tech>
Co-authored-by: Tim Beermann <beermann@osism.tech>

Homer: Changed color scheme of dark mode.

---

roles/netbox/README.rst
roles/netbox/defaults/main.yml

The initializers where a part of the Docker image and where then extracted into a Netbox plugin. Because of this is it necessary to enable the initializers plugin by default.

netbox: enable netbox_initializers by default

---

roles/netbox/templates/initializers/device_roles.yml.j2

We are using dedicated load balancers in a new environment and therefore need this new device type.

netbox: add device role loadbalancer

---

roles/manager/templates/docker-compose.yml.j2

manager: add /opt/state to the conductor service

---

roles/manager/templates/docker-compose.yml.j2

This allows a persistent local directory to be used for storage when using SQLite as the DB backend.

manager: add /opt/state to the ara-server service

---

roles/cgit/defaults/main.yml
roles/keycloak/defaults/main.yml
roles/manager/defaults/main.yml
roles/netbox/defaults/main.yml
roles/patchman/defaults/main.yml
roles/phpmyadmin/defaults/main.yml

In the Nexus role, the parameters are still used in various places. They remain there and are removed with a Followup PR.
Part of osism/ansible-collection-services#720

Remove unused *_traefik_path_prefix & *_traefik_host variables

---

roles/manager/tasks/service.yml

manager: copy osismclient bash completion script

---

roles/manager/tasks/service.yml

In certain constellations it can happen that the osismclient container is not yet available or cannot be used at the moment. To prevent the entire manager deployment from failing, the error is simply ignored here as a workaround.
Closes osism/issues#418

manager: do not fail when osismclient container is not yet there

---

roles/manager/templates/docker-compose.yml.j2

Required to be able to e.g. read available playbooks

manager: add /interface to the osismclient container

---

roles/docker/README.rst
roles/docker/defaults/main.yml
roles/docker/tasks/main.yml

With the docker_facts argument it is possible to disable the docker fact files.

docker: add docker_facts argument

---

roles/zuul/defaults/main.yml

Rename zuul_tag variable to zuul_zuul_tag for consistency. Keep definition blocks in alphabetic ordering.

Update container versions in zuul role

---

roles/hddtemp/README.rst
roles/hddtemp/defaults/main.yml
roles/hddtemp/handlers/main.yml
roles/hddtemp/tasks/install-Debian.yml
roles/hddtemp/tasks/install-RedHat.yml
roles/hddtemp/tasks/main.yml
roles/hddtemp/tasks/service-Debian.yml
roles/hddtemp/tasks/service-RedHat.yml

Closes osism/ansible-collection-services#822

hddtemp: use lm-sensors on Ubuntu 22.04

---

roles/hddtemp/tasks/install-Debian.yml

Module drivetemp is needed by lm-sensors to able monitor disks and nvme's

Add: Kernelmodule drivetemp

---

roles/openstackclient/tasks/package-Debian.yml

Role openstackclient: Remove all "Wait for apt lock“ tasks

---

roles/osquery/tasks/install-Debian.yml

Role osquery: Remove all "Wait for apt lock“ tasks

---

roles/bird/tasks/install-Debian.yml

Role bird: Remove all "Wait for apt lock“ tasks

---

roles/frr/tasks/install-Debian.yml

Role frr: Remove all "Wait for apt lock“ tasks

---

roles/fail2ban/tasks/install-Debian.yml

Role fail2ban: Remove all "Wait for apt lock“ tasks

---

roles/clamav/tasks/install-Debian.yml

Role clamav: Remove all "Wait for apt lock“ tasks

---

roles/netdata/tasks/install-Debian.yml

Role netdata: Remove all "Wait for apt lock“ tasks

---

roles/lldpd/tasks/install-Debian.yml

Role lldpd: Remove all "Wait for apt lock“ tasks

---

roles/cephclient/tasks/package-Debian.yml

Role cephclient: Remove all "Wait for apt lock“ tasks

---

roles/containerd/tasks/install-Debian.yml

Role containerd: Remove all "Wait for apt lock“ tasks

---

roles/tang/tasks/install-Debian.yml

Role tang: Remove all "Wait for apt lock“ tasks

---

roles/smartd/tasks/install-Debian.yml

Role smartd: Remove all "Wait for apt lock“ tasks

---

roles/hddtemp/tasks/install-Debian.yml

Role hddtemp: Remove all "Wait for apt lock“ tasks

---

roles/rsyslog/tasks/install-Debian.yml

Role rsyslog: Remove all "Wait for apt lock“ tasks

---

roles/chrony/tasks/install-Debian.yml

Role chrony: Remove all "Wait for apt lock“ tasks

---

roles/patchman_client/tasks/install-Debian.yml

Role patchman_client: Remove all "Wait for apt lock“ tasks

---

roles/manager/tasks/install-Debian.yml

Role manager: Remove all "Wait for apt lock“ tasks

---

roles/wireguard/README.rst
roles/wireguard/defaults/main.yml
roles/wireguard/handlers/main.yml
roles/wireguard/tasks/main.yml
roles/wireguard/templates/client.conf.j2
roles/wireguard/templates/server.conf.j2

In a production environment, we want to allow for multiple users to be able to connect to the wireguard VPN simultaneously, so we add the option to create a peer configuration for each of them.
Also adapt the role to running on recent Ubuntu versions, where the module is available in the kernel by default.

Refactor wireguard role to allow multiple clients

---

.ansible-lint

Mock missing modules and disable args rule because of the upstream issue.

Ansible-lint: Mock missing modules

---

roles/docker/tasks/install-docker-Debian.yml

Since we allow pinning the version of Docker* packages, it may happen that we explicitly want to perform a downgrade. Accordingly, a downgrade must be allowed.
Closes osism/issues#463

docker: allow downgrade of docker* packages

---

roles/squid/defaults/main.yml

Both quay.io and archive.ubuntu.com have subdomains that may be used in downloading content, like cdn03.quay.io and de.archive.ubuntu.com. Allow all subdomains to avoid blocking things.

squid: update allowed addresses

---

roles/squid/defaults/main.yml

Packagecloud.io uses Cloudfront as a CDN. Since this is done via HTTP redirect, a whitelist entry is necessary.

squid: add .cloudfront.net to whitelist

---

roles/manager/templates/docker-compose.yml.j2

Required to share keys with the *-ansible containers.

manager: add share volume to the osismclient service

---

roles/manager/tasks/service.yml

By default /bin/sh is used. To be able to use -o pipefail the
use of /bin/bash is required.

manager: set executable for "Wait for an healthy manager service"

---

roles/frr/defaults/main.yml
roles/frr/templates/frr_loadbalancer.conf.j2

Allow loadbalancers to advertise IPs with a higher metric in order to support active/passive scenarios.

frr: Add backup config for loadbalancer

---

roles/manager/tasks/service.yml

Netbox availability sometimes takes a long time. Since the inventory reconciler is only healthy when the Netbox is usable, a very long wait (1000 seconds) is intentionally made here.

manager: increase wait for healty services

---

roles/manager/templates/docker-compose.yml.j2

Required to be able to inspect running containers on the manager itself.

manager: add /var/run/docker.sock to osismclient

---

roles/netbox/README.rst
roles/netbox/defaults/main.yml
roles/netbox/tasks/config-netbox.yml
roles/netbox/tasks/config-postgres.yml
roles/netbox/templates/config-netbox-database.j2
roles/netbox/templates/docker-compose.yml.j2
roles/netbox/templates/env/netbox.env.j2

This way it is possible to speedup the netbox initialization with the help of a prepare init.sql file that is part of the configuration repository.

netbox: support use of an init.sql file

---

.ansible-lint
requirements.yml

Closes #1019
Kolla toolbox can´t be integrated at this time, because the source
does not match with ansible standards.

Ansible: Use requirements.yml for collections

---

roles/netbox/templates/docker-compose.yml.j2

* fix depends_on condition for netbox-worker service to wait for netbox service to be healthy before starting
* add networks configuration for netbox-worker service to only join the default network

netbox: improve start of the worker service

---

roles/squid/defaults/main.yml

Refactor squid_allowed_addresses to use defaults and extra lists for better flexibility and maintainability

squid: refactor squid_allowed_addresses

---

roles/manager/templates/docker-compose.yml.j2

Required by the new ansible.cfg merge feature.

manager: add configuration repository to the inventory-reconciler

---

roles/zuul/defaults/main.yml

The Zuul project has moved publishing their container images to quay.io, update the image references accordingly.
Also update to use the current latest tagged versions for both Zuul and Nodepool.

zuul: Update image references

---

roles/squid/defaults/main.yml

So Debian based servers can download packages.

squid: Add .debian.org to allowed targets

---

README.md
roles/thanos_sidecar/README.rst
roles/thanos_sidecar/defaults/main.yml
roles/thanos_sidecar/handlers/main.yml
roles/thanos_sidecar/meta/main.yml
roles/thanos_sidecar/tasks/config.yml
roles/thanos_sidecar/tasks/main.yml
roles/thanos_sidecar/tasks/service.yml
roles/thanos_sidecar/templates/docker-compose.yml.j2

This PR adds Thanos sidecar role.
Note:
- The current version does not implement the option where Thanos sidecar could write collected Prometheus metrics to the object storage. 
- The current version does not implement grpc communication  over TLS
- This version allows some (external) Thanos queriers to query testbed metrics via Thanos sidecar. 
related to https://github.com/SovereignCloudStack/issues/issues/481

thanos_sidecar: add thanos sidecar role

---

roles/docker/README.rst
roles/docker/defaults/main.yml
roles/docker/tasks/install-docker-Debian.yml

This is necessary so that the cache is always updated when the repository is added.

docker: force cache update

---

roles/wireguard/tasks/main.yml

This way the preshared key will not be logged.

wireguard: use no_log for "Copy client configuration files"

---

roles/zuul/defaults/main.yml
roles/zuul/tasks/template_tasks.yml
roles/zuul/templates/docker-compose.yaml.j2
roles/zuul/templates/env/nodepool_builder.env.j2
roles/zuul/templates/env/nodepool_launcher.env.j2
roles/zuul/templates/zuul.conf.j2

This PR enables the configuration of Zuul Scheduler and Zuul Nodepool builder and launcher to emit metrics to the statsd receiver.
For configuring the Zuul Scheduler, the zuul.conf file should be adjusted, see https://zuul-ci.org/docs/zuul/latest/configuration.html#attr-statsd.
For the configuration of the Zuul Nodepool launcher and builder, the environment variables should be set, see https://zuul-ci.org/docs/nodepool/latest/installation.html#statsd-configuration.

Add Statsd configuration options for Zuul

---

roles/zuul/defaults/main.yml
roles/zuul/templates/docker-compose.yaml.j2
roles/zuul/templates/zoo.cfg.j2

This PR enables the configuration of Zuul's Zookeeper component to expose metrics on the specified port.
see https://zookeeper.apache.org/doc/current/zookeeperMonitor.html

Add metrics configuration option for Zookeeper

---

roles/docker/tasks/install-docker-Debian.yml

Over time, the dependencies in the Docker repository have changed. It should therefore be ensured that packages from the past no longer remain installed.

docker: ensure that some packages are not installed

---

roles/scaphandre/templates/docker-compose.yml.j2

This is the only way to be able to access the /sys/devices files.

scaphandre: run privileged

---

molecule/delegated/vars/openstackclient.yml
roles/cephclient/tasks/package-Debian.yml
roles/containerd/tasks/install-Debian.yml
roles/docker/tasks/install-docker-Debian.yml
roles/falco/tasks/install-Debian.yml
roles/netdata/tasks/install-Debian.yml
roles/openstackclient/tasks/package-Debian.yml
roles/osquery/tasks/install-Debian.yml

cf. https://github.com/osism/issues/issues/849
Add task to remove old repository entry in following roles (cf. https://github.com/osism/ansible-collection-services/pull/1270): 
¹ **Note:** New capabilities in [falcoctl](https://falco.org/blog/falco-0-37-0/#new-falcoctl-capabilities) to download and build kernel drivers, replacing the old falco-driver-loader script. **Needs to be fixed!** Issue opened: https://github.com/osism/issues/issues/850

Add tasks to remove old architecture-dependent repository

---

roles/keycloak/tasks/create-database.yml

The namespace has to be created before the "Deploy keycloak database on CloudNativePG cluster" task.

keycloak: create namespace

---

roles/cloudnative_pg/tasks/main.yml

This will avoid the following issue when running the keycloak role after the cloudnative_pg role.
no endpoints available for service "cnpg-webhook-service"

cloudnative_pg: wait for webhook

---

roles/docker/vars/Debian-family.yml
roles/docker/vars/RedHat-family.yml

Revert this until we have a better approach to set the docker version on the manager node.
This reverts commit 17e834a8e6ceb1a8482d795e7e652e1a7cc9126a.

Revert "docker: use version 26.0.2 (#1369)"

---

roles/docker/vars/Debian-family.yml
roles/docker/vars/RedHat-family.yml

After the changes in osism/cfg-generics it is now possible to use pinned versions of Docker + all Ansible collections that are required to upgrade the manager service. This means that we can now upgrade the Docker version to 26.0.2.
This reverts commit 9e860541c5728773b5e3ce02d8b57266a64299df.

docker: use version 26.0.2 (pt. 2)

---

.zuul.yaml

The MariaDB service on CentOS 9 cannot be started properly. Therefore the test on CentOS 9 is temporarily deactivated in order not to restrict the development itself. CentOS 9 is not yet supported.

zuul: disable manager centos9 job

---

.zuul.yaml
molecule/delegated/prepare/manager.yml

Since we are working within a venv, but the python-3docker package is installed via apt, it must be installed manually in the venv so that the facts of osism.services.docker work.

zuul: install docker with pip for the manager role

---

roles/manager/handlers/main.yml

More privileges are not required for the handlers
that uses docker-compose commands.

manager: remove become from handlers where not required

---

roles/manager/tasks/service.yml
roles/openstackclient/handlers/main.yml

More privileges are not required for the handlers
using docker-compose commands.
Related to 14d51ce2b0c751c45f69356950020a88605a7c58

Remove some more become from handlers where not required

---

molecule/delegated/tests/rsyslog.py
roles/rsyslog/tasks/main.yml
roles/rsyslog/vars/CentOS-dist.yml
roles/rsyslog/vars/Debian-dist.yml
roles/rsyslog/vars/Ubuntu-dist.yml

rsyslog: use prefix variables for OS specific defaults

---

roles/chrony/tasks/main.yml
roles/chrony/vars/Debian-family.yml
roles/chrony/vars/RedHat-family.yml

chrony: use prefix variables for OS specific defaults

---

roles/traefik/templates/docker-compose.yml.j2

It's unused and not necessary.

traefik: remove wrong osism.yml volume

---

roles/traefik/defaults/main.yml
roles/traefik/templates/docker-compose.yml.j2
roles/traefik/templates/traefik.yml.j2

With traefik_extra_ports it's possible to manage
additional ports with traefik.
E.g. to manage port 5000 and port 8774:
traefik_extra_ports:
- 5000
- 8774

traefik: allow extra ports

---

roles/traefik/defaults/main.yml
roles/traefik/tasks/config.yml
roles/traefik/templates/docker-compose.yml.j2
roles/traefik/templates/dynamic.yml.j2

With the traefik_configuration_dynamic parameter it's possible to define additional services via the file provider.
This will add a router that routes all requests on api-81-163-192-117.traefik.me to the service-horizon service.
traefik_configuration_dyanmic:
tcp:
services:
service-horizon:
loadBalancer:
servers:
- address: "192.168.16.254:443" routers: router-horizon: rule: "HostSNI(`api-81-163-192-117.traefik.me`)" service: service-horizon

traefik: allow dynamic service configuration

---

roles/docker/defaults/main.yml
roles/docker/handlers/main.yml

With the docker_throttle_restart parameter it's possible to throttle the service restarts. By default service restarts will not be throttled.
Part of osism/issues#813

docker: allow to throttle docker service restarts

---

roles/docker/defaults/main.yml
roles/docker/handlers/main.yml

Can be enabled with the docker_wait_after_restart parameter. Disabled by default.
The seconds to wait can be set with the
docker_wait_after_restart_seconds parameter. The default value is 60.

docker: allow to wait some time after docker serivce restart

---

releasenotes/notes/add-molecule-testinfra-a7d15bed7af6bd86.yaml
releasenotes/notes/add-molecule-zuul-job-e07b844fc1022e36.yaml
releasenotes/notes/homer-remove-kibana-d0c81feafe1af25e.yaml
releasenotes/notes/manager-ara-server-mariadb-volume-type-cb20abe7946ecbed.yaml
releasenotes/notes/manager-ara-server-new-parameters-4dde69d8d501ebc4.yaml
releasenotes/notes/manager-ara_server_mariadb_healthcheck-71e116352e2cf62b.yaml
releasenotes/notes/manager-fs.inotify.max_user_instances-2a71c3ac11e8da69.yaml
releasenotes/notes/manager-improve-wait-for-an-healthy-manager-services-fc6132d1cfeed397.yaml
releasenotes/notes/manager-listener-enable-8be154e1398e0ff9.yaml
releasenotes/notes/manager-mariadb-MARIADB_AUTO_UPGRADE-7b3812dd9a8dd91c.yaml
releasenotes/notes/manager-more-healthchecks-2819198e29a80405.yaml
releasenotes/notes/manager-only-copy-bash-completion-with-celery-integration-b50dadda5e9b897f.yaml
releasenotes/notes/manager-opensearch-protocol-6899e3ff20ec511b.yaml
releasenotes/notes/manager-osism-update-docker-b519e7ad5bbeabcb.yaml
releasenotes/notes/manager-remove-osism-mirror-e621c82c1d666cbf.yaml
releasenotes/notes/manager-resource-limits-8dc65134a0738a8d.yaml
releasenotes/notes/manager-sources-configurable-98bb9a9b6fdc68c9.yaml
releasenotes/notes/manager-update-wrapper-arguments-2f5ea72ac68aa8ec.yaml
releasenotes/notes/mariadb-use-healthcheck.sh-script-85633547115b539c.yaml
releasenotes/notes/netbox-add-healthcheck-3dbaa2f0fca8c19d.yaml
releasenotes/notes/netbox-netbox_postgres_volume_typ-ade52938ba4a2185.yaml
releasenotes/notes/remove-patchman-686a14202925b24b.yaml
releasenotes/notes/squid-add-healthcheck-6adfb0f696672c2b.yaml
releasenotes/notes/squid-remove-whitelist-42419d9868936912.yaml
releasenotes/notes/squid-version-5.7-23.04_beta-e05f0f4d729abf6b.yaml
releasenotes/notes/traefik-add-healthcheck-5c0f41f233cb60d0.yaml
releasenotes/notes/wait-for-healthy-containers-aa18406aa766d3a7.yaml
releasenotes/notes/zuul-volume-settings-dfdcc32a900018cb.yaml

We manage the release notes again in the central osism/release and osism/osism.github.io repository.

Remove release notes

---

roles/docker/defaults/main.yml
roles/docker/tasks/install-docker-Debian-family.yml
roles/docker/tasks/install-docker-RedHat-family.yml

With the boolean docker_python_install parameter it is possible to enable and disable the installation of the Python docker bindings.

docker: add docker_python_install parameter

---

roles/manager/defaults/main.yml
roles/manager/templates/docker-compose.yml.j2

With the manager_enable_openstack parameter it is possible to disable the openstack integration. This is useful for clusters without OpenStack. The default value of the manager_enable_openstack parameter is true.

manager: add manager_enable_openstack parameter

---

roles/cephclient/defaults/main.yml
roles/cephclient/templates/docker-compose.yml.j2
roles/openstackclient/defaults/main.yml
roles/openstackclient/templates/docker-compose.yml.j2

Some containers liek cephclient and openstackclient are using container networking, causing the outside of the container to be reached via NAT.
We've ran in to an issue where the NAT was done with the source-IP address of our management interface instead of the dummy interface that should be used, causing the packets to reach it's destination with the wrong source-IP.
I think this might even be a bug in Docker's networking, as it honoured the route but dismissed the 'src' flag. Quite frankly we are fine with running the containers in host networking mode, so there should be an option to do so if desired IMO.

Add option for host networking instead of container networking

---

molecule/delegated/prepare.yml

This is required to be able to create the external traefik network.

molecule: always install requests

---

.zuul.yaml
molecule/delegated/tests/fail2ban.py

It makes no sense to skip a unit test on a specific distro version. Either we have to skip the whole molecule test for Ubuntu 24.04 or the failed test is ok until upstream fixed the LP#2055114.

molecule: also check on ubuntu 24.04

---

molecule/delegated/tests/cephclient/container.py
roles/cephclient/tasks/container.yml

The crushtool is today only available in the ceph-base package. The ceph-base package installs a lot of requirements in the cephclient container image. Because of that we remove the crushtool wrapper. The crushtool can be used on the Ceph control nodes.

cephclient: remove crushtool wrapper

---

roles/traefik/defaults/main.yml
roles/traefik/templates/traefik.env.j2

Pilot configuration has been removed in v3.

traefik: remove parameter traefik_pilot_dashboard

---

roles/netbox/handlers/main.yml

The initial DB bootstrap can take some time on slow manager nodes.

netbox: wait up to 10 minutes for netbox

---

molecule/delegated/tests/hddtemp/debian.py
roles/hddtemp/defaults/main.yml
roles/hddtemp/tasks/install-Debian-family.yml

Check if drivetemp module is available before loading on Debian and Ubuntu.
Reverts changes from https://github.com/osism/ansible-collection-services/pull/1467

hddtemp: Add drivetemp module check

---

roles/openstackclient/templates/openstack.j2

This fix might help to solve the terminal state problem described in https://github.com/osism/issues/issues/1078
Adding a "exec" seems to solve that problem.

trying to fix the terminal state problem

---

roles/squid/templates/osism.conf.j2

Squid will allocate memory for caching based on the maximum file descriptors. If not specified in the squid config, it will pull the default value from the system limits. On CentOS 9 the limit is much higher than on Debian/Ubuntu (1073741816 vs 1048576). This will lead to page faults when spinning up the container on CentOS.
This commit adds the ``max_filedescriptors`` limit to the squid config with the default value of Debian/Ubuntu preventing the crash.

squid: Add max_filedescriptors limit to config

---

roles/squid/defaults/main.yml
roles/squid/handlers/main.yml
roles/squid/tasks/install-Debian-family.yml
roles/squid/tasks/install-RedHat-family.yml
roles/squid/tasks/main.yml

Use the same mechanism as in the netbox role to wait for a healthy service

squid: Handle the start of the service gracefully

---

roles/cephclient/tasks/clean-container.yml
roles/cephclient/tasks/clean-package-Debian-family.yml
roles/cephclient/tasks/clean-package-RedHat-family.yml
roles/cephclient/tasks/rook.yml

This was tested using a testbed deployment and a cephclient installation using `package`-method as well as `container`-method prior to change the installation method to `rook` followed by an `osism apply cephclient` again to verify the cleanup of both existing installation methods.
Implements: https://github.com/osism/issues/issues/1038

add cleanup possible legacy cephclient wrapper installations

---

molecule/delegated/tests/netbox.py
roles/netbox/templates/configuration.py.j2

The default directory /etc/netbox/scripts does not exist in the NetBox container, therefore, the attempt to add the script failed.
This commit sets the existing directory /opt/netbox/netbox/scripts as the default.
For issue replication:
- Add a new data source to the Netbox (navigate to Operations/Data sources) and sync it.
-  Try to add a script from added data source in Netbox (navigate to Customization/Scripts)

Fix default SCRIPTS_ROOT path in Netbox configuration.py

---

roles/manager/templates/docker-compose.yml.j2
roles/manager/vars/Debian-family.yml
roles/manager/vars/RedHat-family.yml

This way it is possible to use the manager service on Ubuntu/Debian as well as on CentOS.

manager: fix handling of CA certificates

---

roles/scaphandre/defaults/main.yml
roles/scaphandre/templates/docker-compose.yml.j2

Scaphandre is only capable to fetch detailed information about process execution for processes which have access to the global pid namespace.
This enables the parameter "pid: host" for the docker compose file. (https://docs.docker.com/reference/cli/docker/container/run/#pid)

share pids with host

---

roles/frr/defaults/main.yml
roles/frr/tasks/main.yml
roles/frr/templates/frr_k3s_cilium.conf.j2
roles/frr/templates/frr_leaf.conf.j2
roles/frr/templates/frr_loadbalancer_external_uplink.conf.j2

All frr_uplinks__* parameters will be merged with the frr_uplinks parameter. This way it is possible to add host specific frr_uplinks via the host vars.

frr: allow to use frr_uplinks__* parameters in host vars

---

roles/docker/defaults/main.yml
roles/docker/templates/daemon.json.j2

With the docker_storage_containerd_snapshotter parameter it is possible to enable the experimental container-snapshotter feature.
https://docs.docker.com/engine/storage/containerd/

docker: add docker_storage_containerd_snapshotter parameter

---

roles/manager/templates/docker-compose.yml.j2

This reverts commit c4052116ac22afb27be65667ec58eb78204b47fb.
We'll use the cloud profiles instead of the environment variables.

Revert "manager: make openstack env available in the osismclient"

---

roles/nexus/defaults/main.yml
roles/nexus/tasks/main.yml

With the nexus_force_init parameter it is possible to force the initialisation of the service.

nexus: add nexus_force_init parameter

---

roles/netbox/templates/configuration.py.j2

In the case of multiple Netbox plugin configuration items, e.g.:
```yaml
netbox_plugins_config:
netbox_config_diff:
USERNAME: "admin"
PASSWORD: "YourPaSsWoRd"
netbox_topology_views:
static_image_directory: "netbox_topology_views/img"
```
Netbox's configuration.py is rendered as follows:
```python
PLUGINS_CONFIG = {
'netbox_config_diff': {
'USERNAME': 'admin',
'PASSWORD': 'YourPaSsWoRd',
}
'netbox_topology_views': {
'static_image_directory': 'netbox_topology_views/img',
}
}
```
A comma between two dict items is missing. 
This PR fixes the above

Fix rendering of netbox plugins configuration

---

roles/wireguard/defaults/main.yml
roles/wireguard/templates/client.conf.j2

With the wireguard_dns parameter it is possible to set the DNS server.
Related to osism/cloud-in-a-box#336

wireguard: add wireguard_dns parameter

---

roles/wireguard/defaults/main.yml

This will avoid the following issue:
object of type 'NoneType' has no len(). object of type 'NoneType' has no len()

wireguard: use empty string as default for wiregurad_dns

---

roles/manager/templates/docker-compose.yml.j2

The inventory reconciler service depends on all *-ansible services because of the /interface files.

manager: fix depends_on of the inventory reconciler service

---

roles/manager/defaults/main.yml
roles/manager/templates/docker-compose.yml.j2

The `osism_netbox_image` is no longer build and replaced with the generic `osism_image`.
Part of https://github.com/osism/issues/issues/1223

Remove usage of `osism_netbox_image` in manager role

---

roles/manager/templates/docker-compose.yml.j2
roles/netbox/templates/initializers/custom_fields.yml.j2

Add a custom field to netbox devices to allow to overwrite ironic parameters set in the manager's `conductor.yml`.
Part of https://github.com/osism/issues/issues/1224

Add netbox custom field for ironic parameters

---

roles/netbox/templates/initializers/custom_fields.yml.j2

Allow to overwrite the default dnsmasq DHCP tag
Also hide most of the custom fields in the UI if not set.

netbox: add custom field dnsmasq_dhcp_tag

---

roles/netbox/templates/initializers/device_roles.yml.j2

An OOB Leaf is an Access Leaf with the out-of-band tag.

netbox: remove OOB Leaf device role

---

roles/manager/defaults/main.yml
roles/manager/templates/env/inventory-reconciler.env.j2

With manager_inventory_reconciler_mode it's possible to set the mode of the inventory reconciler. Supported values are manager and metalbox at the moment.

manager: make it possible to set the inventory-reconciler mode

---

roles/manager/defaults/main.yml
roles/manager/tasks/service.yml

The manager_service_manual_start parameter allows to do a manual start with docker compose. Sometimes this is more reliable when deploying the manager the first time.

manager: add manager_service_manual_start parameter

---

roles/manager/defaults/main.yml
roles/manager/templates/docker-compose.yml.j2

With the boolean parameter manager_enable_watchdog it's possible to configure the watchdog service.

manager: make it possible to disable the watchdog service

---

roles/netbox/templates/initializers/custom_fields.yml.j2

Add a text custom field to store device-specific secrets (Ansible vault encrypted) in NetBox. The field is optional and hidden unless set.

netbox: add secrets custom field for devices

---

roles/manager/templates/wrapper/osism.j2

Split the -it flag into separate -i and -t flags. Always enable stdin (-i) but only allocate a pseudo-TTY (-t) when running in interactive mode. This ensures proper stdin handling for non-interactive commands while preserving TTY allocation for interactive sessions.

manager: fix stdin handling in osism wrapper

---

roles/dnsmasq/defaults/main.yml
roles/dnsmasq/tasks/config.yml
roles/dnsmasq/templates/dnsmasq.conf.j2

Enable network boot (PXE) capabilities by adding support for dhcp-boot options. This allows configuration through the dnsmasq_dhcp_boot variable with group-based merging support similar to other dhcp options.

dnsmasq: add dhcp-boot configuration support

---

molecule/delegated/vars/httpd.yml
roles/httpd/defaults/main.yml
roles/httpd/tasks/main.yml
roles/httpd/tasks/sonic-ztp.yml
roles/httpd/templates/ztp.json.j2

Adds Zero Touch Provisioning (ZTP) capability for SONiC switches through the httpd role. This enables automated firmware installation, SSH key deployment, and configuration database provisioning via HTTP.

httpd: add SONiC ZTP support

---

roles/dnsmasq/defaults/main.yml
roles/dnsmasq/tasks/config.yml
roles/dnsmasq/templates/dnsmasq.conf.j2

Add support for DHCP user class configuration in dnsmasq role with new dnsmasq_dhcp_userclass variable and template support.

dnsmasq: add dhcp-userclass support

---

roles/dnsmasq/defaults/main.yml
roles/dnsmasq/tasks/config.yml

This reverts commit c15d75ed4932e52f3c35be0a3cf957053c419939.

Revert "dnsmasq: ignore some extra vars in metalbox mode"

---

roles/httpd/tasks/main.yml
roles/httpd/templates/docker-compose.yml.j2

Changes _httpd_loopback_ipv6 fact to collect all IPv6 addresses with global scope from the interface instead of just the first one. Updates docker-compose template to iterate through all collected IPv6 addresses when binding ports.
AI-assisted: Claude Code

httpd: bind to all global IPv6 addresses

---

.github/workflows/publish-collection.yml

This reverts commit 340f9771656292038c94d2e33257f264d243699c.
Does not work with current Ansible version.

Revert "chore(deps): update dependency python to 3.13 (#1970)"
